var SPACE_MAIN_DOMAIN=parent.g_Main_Domain,SPACE_MAIN_READ_DOMAIN=parent.g_R_Domain,SPACE_MAIN_WRITE_DOMAIN=parent.g_W_Domain,CGI_BLOG_DOMAIN=parent.g_NewBlog_Domain,CGI_BLOG_R_DOMAIN=/pengyou\.com$/.test(location.hostname)?"br."+QZONE.FP._t.g_DPrefix+"pengyou.com":"br."+QZONE.FP._t.g_DPrefix+"qzone.qq.com",IMGCACHE_DOMAIN=parent.imgcacheDomain,STYLE_DOMAIN=parent.siDomain,CGI_MSGBOARD_DOMAIN=parent.g_MsgBoard_Domain,CGI_MSGBOARD_PATH="/cgi-bin/new/",CGI_BLOG_PATH="/cgi-bin/blognew",CGI_PRIVATEBLOG_PATH=
"/cgi-bin/privateblog",CGI_DRAFT_PATH="/cgi-bin/draft",IMGCACHE_BLOG_V5_PATH="/qzone/newblog/v5",IMGCACHE_BLOG_V6_PATH="/qzone/app/blog/v6",IMGCACHE_BLOG_PENGYOU_PATH="/qzone/app/blog/pengyou",IMGCACHE_BLOG_PATH="/qzone/newblog",CONTENT_COMMENT_NUM=19990210==QZONE.FP.getQzoneConfig().ownerUin?45:15,MSGCNT_PER_PAGE=6,MAX_COMMENT_LEN=4500,MAX_BLOG_LEN=153600,MAX_BLOG_HTML_LEN=307200,MAX_BLOG_TITLE_LEN=128,BLOG_VERIFY_CODE=8000103,MSG_VERIFY_CODE=8000102,LIST_TITLE_NUM=15,VERIFY_DOMAIN="ptlogin2.qq.com",
DEFAULT_PORTRAIT_IMGURL="/qzone_v4/client/userinfo_icon/5001.gif",LOADING_GIF="/qzone/newblog/v5/editor/css/loading.gif",BOARD_INFO_URL="http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/board.html",INSERT_MEDIA_FORBIDDEN=!1,CLICK_STREAM_RATE=0.3,FRAME_ID="tblog",MSG_FRAME_ID="tgb",FRONT_AUTO_DRAFT_LENGTH=2;window.console||(window.console={log:function(){},print:function(){},dir:function(){}});QZFL.console.log||(QZFL.console.log=QZFL.emptyFn);
var PAGE_CACHE={BLOG_CACHE_MASTER_KEY:"QZONE_BLOG_CACHE_MANAGER",BLOG_CACHE_KEY_LIST:"QZONE_BLOG_CACHE_MANAGER_KEY_LIST",CACHE_WIN:QZONE.FP._t,add:function(a,b,c){try{return this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY]||(this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY]={},this.CACHE_WIN[this.BLOG_CACHE_KEY_LIST]={}),this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY][a]={data:b,expired:1E3*parseInt(c,10)+(new Date).getTime()},this.CACHE_WIN[this.BLOG_CACHE_KEY_LIST][a]=!0}catch(d){return!1}},get:function(a){try{var b=
QZONE.FP._t[this.BLOG_CACHE_MASTER_KEY][a];if(b){if(!b.expired||0>b.expired)return b.data;var c=(new Date).getTime();if(b.expired>c)return b.data;this.remove(a)}}catch(d){}return null},remove:function(a){try{this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY][a]=void 0}catch(b){console.log(b)}},clean:function(a){if(a)this.remove(a);else try{this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY]=void 0}catch(b){console.log(b)}}},blogLoginFnList=[];
function loginCallback(){try{for(;0<blogLoginFnList.length;)blogLoginFnList.shift()()}catch(a){}}function getParentByClass(a,b){try{for(;a&&a.offsetParent;){if(0<=a.className.indexOf(b))return a;a=a.offsetParent}}catch(c){}return null}function getElementsByTagName(a,b,c){a=a||document;var d=[];a=a.getElementsByTagName(b);for(b=0;b<a.length;++b)a[b].getAttribute("name")==c&&d.push(a[b]);return d}
var loadXMLAsync=function(a,b,c,d,e,f,g){uriInfo=QZFL.util.URI(b);if(/(qq|pengyou)\.com$/.test(uriInfo.host)){var h="http://"+/([a-z,A-Z,0-9,\-,_,\.]+\.com)$/i.exec(uriInfo.host)[1]+"/",k=uriInfo.host,l=h+(QZBlog.Logic.isInPengyou?"py_proxy.html":"proxy.html");h=="http://"+IMGCACHE_DOMAIN+"/"&&(l="http://"+IMGCACHE_DOMAIN+"/ac/qzone/"+(QZBlog.Logic.isInPengyou?"py_proxy.html":"proxy.html"));for(var h=document.getElementsByTagName("iframe"),m=0;m<h.length;m++){var n=!1;try{n=0==h[m].src.indexOf(l)}catch(u){}if(n){callBackHsmp[k]||
"undefined"==typeof callBackHsmp[k]?("undefined"==typeof callBackHsmp[k]&&(callBackHsmp[k]=[]),callBackHsmp[k][callBackHsmp[k].length]={callback:c,xID:a,xUrl:b,err_callback:d,nocache:e,data:f,returnType:g}):h[m].contentWindow.loadXMLAsync(a,b,c,d,e,f,g);return}}callBackHsmp[k]||(callBackHsmp[k]=[{callback:c,xID:a,xUrl:b,err_callback:d,nocache:e,data:f,returnType:g}],createProxy(l))}else alert("\u8de8\u57df\u7684\u8d44\u6e90\u8bbf\u95ee\u7981\u6b62("+uriInfo.host+")")},callBackHsmp=[],createProxy=
function(a){for(var b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)if(-1!=b[c].src.indexOf(a))return;c=document.createElement("iframe");$("proxy")?$("proxy").appendChild(c):document.body.insertBefore(c,null);c.width=0;c.height=0;c.src=a};
function doFill(a,b,c,d){c="undefined"==typeof c?0:c;if(!b)return"";var e=/<%=@([#~&\w]+)%>/g,f=!!b.xml,g="<%repeat_"+c+'\\s*match="([^"]+)"[^%]*%>',h=RegExp(g,"g"),k=RegExp("<%repeat_"+(c+1)+' match="([^"]+)"');if(null==a.match(RegExp(g)))return rt.error("\u6ca1\u6709\u627e\u5230\u8282\u70b9<%repeat_"+c+"%>"),"";for(var g=a.match(h),l=0,h=0;h<g.length;h++){var m=g[h],n=m.replace(/^.*match=\"|\".*$/g,""),l=a.indexOf(m),u=a.indexOf("<%_repeat_"+c+"%>",l),w=a.substring(l,u+13),l=l+m.length,l=a.substring(l,
u),n=f?b.selectNodes(n):objSelectNodes(b,n),u=[],s=n.length;0<m.indexOf("repeat_num")&&(m=m.replace(/^.*repeat_num=\"|\".*$/g,""),isNaN(m)||(s=Math.min(s,parseInt(m,10))));for(m=0;m<s;m++){var p=n[m],r=l;null!=l.match(k)&&(r=doFill(l,p,c+1,d));p=r;if(0==m){var t=r.match(e);if(null==t)t=[];else if(d){for(var r=[],v={},q=0,x=t.length;q<x;q++)0!=q&&v[t[q]]||(r.push(t[q]),v[t[q]]=!0);t=r.sort().reverse()}}for(r=0;r<t.length;r++)v=t[r].replace(/\W/g,""),q=f?n[m].getAttribute(v):n[m][v],null==q&&f&&null!=
n[m].selectSingleNode(v)&&(q=n[m].selectSingleNode(v).text),null==q&&(q=""),q=q.toString(),p=p.replace(RegExp(t[r],"g"),q.replace(/\$/g,"$$$$"));u[m]=p}a=a.replace(w,QZONE.userAgent.ie?u.join(""):u.join("").replace(/\$/g,"$$$$"))}return a}function objSelectNodes(a,b){/^\//.test(b)&&(b=b.substr(1));var c=b.split("/"),d=a[c.shift()];if(!d)return[];d.sort||(d=[d]);if(0==c.length)return d;for(var e=c.join("/"),f=[],g=0;g<d.length;g++)(c=objSelectNodes(d[g],e))&&0<c.length&&(f=f.concat(c));return f}
function objSelectSingleNode(a,b){var c=objSelectNodes(a,b);return 1<=c.length?c[0]:null}String.prototype.trim=function(){return trim(this)};String.prototype.ltrim=function(){return ltrim(this)};String.prototype.rtrim=function(){return rtrim(this)};String.prototype.toInnerHTML=function(){var a=this.replace(/&/g,"&amp;").replace(/\"/g,"&quot;").replace(/\'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;");return QZONE.userAgent.ie?a.replace(/&apos;/g,"&#39;"):a};
String.prototype.toRealStr=function(){return this.replace(/&quot;/g,'"').replace(/(?:&#39;)|(?:&apos;)/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&#92;/g,"\\")};String.prototype.convCR=function(a){return a?this.replace(/<br \/>/g,"\n"):this.replace(/\n/g,"<br />")};String.prototype.convSP=function(a){return a?this.replace(/&nbsp;/g," "):this.replace(/\x20\x20/g,"&nbsp;&nbsp;")};String.prototype.convHeaderSP=function(){return this.replace(/\n\x20(^\x20)*/ig,"\n&nbsp;$1")};
String.prototype.getRealLength=function(){return this.replace(/[^\x00-\xff]|\n/g,"hh").length};String.prototype.URLencode=function(){return URIencode(this)};String.prototype.getUrlParamValue=function(a){return(a=this.match(RegExp("(\\?|#|&)"+a+"=([^&#]*)(&|#|$)")))?a[2]:""};
String.prototype.cutWord=function(a){var b=this.toRealStr();if(b.getRealLength()<=a||0>=a)return b.toInnerHTML();for(var c="",d=Math.floor(a/2);;)if(c=b.substr(0,d),c.getRealLength()<a-1)d+=Math.floor((a-c.getRealLength())/2);else if(c.getRealLength()>a)d-=Math.floor((c.getRealLength()-a)/2);else{c.getRealLength()!=a&&d<b.length&&!QZBlog.Util.isMultipleByte(b.charCodeAt(d))&&(c=b.substr(0,d+1));break}return c.toInnerHTML()};
function getParameter(a){return(a=location.href.match(RegExp("(\\?|#|&)"+a+"=([^&#]*)(&|#|$)")))?a[2]:""}function getAuthor(a,b,c){a=parseInt(a,10);c=String(c||QZBlog.Util.getLoginUin());var d=!1;return d=(d=b&&QZONE.FP.isAlphaUser())||parseInt(c.substring(c.length-2),10)<a}function BlogXMLselectSingleNode(a,b){var c=BlogXMLselectNodes(a,b);return!c||1>c.length?null:c[0]}
function BlogXMLselectNodes(a,b){for(var c=new XPathEvaluator,d=c.createNSResolver(null==a.ownerDocument?a.documentElement:a.ownerDocument.documentElement),c=c.evaluate(b,a,d,0,null),d=[],e;e=c.iterateNext();)d.push(e);return d}function XMLSelectNodes(a,b){return QZONE.userAgent.ie?a.selectNodes(b):BlogXMLselectNodes(a,b)}function XMLselectSingleNode(a,b){return QZONE.userAgent.ie?a.selectSingleNode(b):BlogXMLselectSingleNode(a,b)}
function isXMLDoc(a){try{return XMLselectSingleNode(a,"/"),!0}catch(b){return!1}}function getXMLNodeText(a){return a?"undefined"!=typeof a.innerText?a.innerText:"undefined"!=typeof a.textContent?a.textContent:a.text:null}function isValidUin(a){if("string"==typeof a&&15<a.length)return!0;a=parseInt(a,10);return!isNaN(a)&&/\d{5,10}/.test(a)?!0:!1}
var QZBlog={Logic:{isInPengyou:!!/pengyou\.com$/.test(location.hostname),isInV6:!0,isSeoPage:!QZONE.FP.getCurrentAppWindow(),isBlogPage:"blog.qq.com"==location.host.toLowerCase(),qqDomainFilter:function(a){return/^http\:\/\/[\w|\.]+\.qq\.com\//i.test(a)||/^http\:\/\/[\w|\.]+\.pengyou\.com\//i.test(a)?a:""}},Util:{}};
QZBlog.CGI_URL=function(){var a=parent.g_NewBlog_Domain,b=QZONE.FP._t.g_DPrefix?QZONE.FP._t.g_DPrefix.replace("os","cnc").replace(".",""):"",c=QZONE.FP._t.g_BLOG_LOCATION_PREFIX||"b1",d=QZONE.FP._t.g_BLOG_LOCATION_LOGIN_PREFIX||"b1",e={msgboard:"/cgi-bin/new/","private":"/cgi-bin/privateblog/",draft:"/cgi-bin/draft/",recycle:"/cgi-bin/recyclebin/",ugc:"/cgi-bin/ugc/",operation:"/cgi-bin/operation/","default":"/cgi-bin/blognew/"},f={b:CGI_BLOG_DOMAIN,bn:QZBlog.Logic.isInPengyou?"%s.pengyou.com":"%s.qzone.qq.com",
loginUser2Bn:QZBlog.Logic.isInPengyou?"%l.pengyou.com":"%l.qzone.qq.com"},g={b:",blog_get_blogbitmap,blog_recommend_self,blog_get_userinfo,blog_one_count,blog_report_audit,blog_get_readerlist,blog_get_count_mutiuin,blog_get_related,blog_set_bitmap,blog_hide_readerlist,blog_get_qqnews,blog_fetch_source,blog_get_taglists,blog_output_tagpagelist,blog_get_setting,set_user_info,get_winninglist,blog_get_spread,readzone_add_unconcern,readzone_get_concern,readzone_get_friendlist,readzone_get_newnum,readzone_get_data,readzone_get_replylist,readzone_get_titlelist_mix,readzone_get_titlelist_single,readzone_get_titletoppage,readzone_set_concern,url_check,ugcblog_get_update_num,ugcblog_clear_update_num,operation_get_recommend,blog_get_unverify,blog_get_interaction,",
bn:",add_comment,get_comment_list,blog_add_comment,blog_add,add_blog,ablog_add,ablog_get_list,ablog_recommit,ablog_del,blog_del_category,blog_del_comment,del_comment,del_blog,blog_del_comment_ic,blog_del_data,blog_batch_del_data,blog_get_category,blog_get_data,get_blog,blog_get_specialtitle,blog_get_titlelist,blog_modify,mod_blog,blog_modify_category,blog_recover_nickname,blog_set_top,mod_blog_effect,add_reply,blog_reply_comment,blog_recommend_self,blog_batch_del_comment,batch_del_comment,mod_blog_cate,blog_get_abstract,blog_get_abstract2,get_abs,blog_del_replycomment,del_reply,blog_modify_right,blog_add_category,op_cate,blog_batch_modify_category,blog_batch_modify_right,mod_blog_right,blog_modify_img,blog_output_data,blog_output_titlelist,blog_output_titlelist2,blog_output_toppage,blog_pass_unverify,blog_modify_tag,blog_generate_feeds,blog_get_media,blog_to_tweet,blogimg_to_tweet,blog_get_datenum,blog_extern_get_data,draft_output_manual_data,draft_output_manual_list,draft_output_manual_list2,draft_del_manual_data,draft_get_manual_data,draft_get_manual_list,draft_set_manual_data,draft_add_blog,draft_modify_blog,draft_get_auto_data,draft_set_auto_data,draft_del_auto_data,draft_auto2manual,draft_output_data,draft_del_data,draft_get_data,draft_output_list,draft_set_data,draft_to_blog,privateblog_add,privateblog_del_data,privateblog_get_data,privateblog_get_specialtitle,privateblog_get_titlelist,privateblog_modify,privateblog_output_data,privateblog_pub2prv,privateblog_prv2pub,privateblog_del_comment,privateblog_batch_prv2pub,privateblog_batch_pub2prv,pwd2c_query_iframe,recyclebin_del,recyclebin_get_list,recyclebin_recover_blog,recyclebin_switch,ugcblog_get_data,ugcblog_add,ugcblog_del_data,ugcblog_get_list_async,",
loginUser2Bn:",blog_quote,quote_blog,"};return{get:function(a,b){var c="http://"+this.getDispatchDomain(a),c=c+(e[b]?e[b]:e["default"]);return c+a},getDispatchDomain:function(e){var k=a,l;for(l in g)if(0<=g[l].indexOf(","+e+",")&&f[l]){e=c+(0<b.length?"."+b:"");k=f[l].replace("%l",d+(0<b.length?"."+b:"")).replace("%s",e);break}return k},getRouterCgiUrl:function(a){a||(a=[QZBlog.Logic.SpaceHostInfo.getLoginUin(),QZBlog.Logic.SpaceHostInfo.getUin()]);return"http://"+CGI_BLOG_R_DOMAIN+"/cgi-bin/blognew/blog_get_route?fupdate=1&g_tk="+
QZBlog.Util.getToken()+"&uinlist="+a.join(",")},setLocatePrefix:function(a){c=QZONE.FP._t.g_BLOG_LOCATION_PREFIX=a},setLoginLocatePrefix:function(a){d=QZONE.FP._t.g_BLOG_LOCATION_LOGIN_PREFIX=a}}}();parent.g_oBlogPortraitList||(parent.g_oBlogPortraitList={});
QZBlog.Util.PortraitManager={portraitSeed:"",getPortraitUrl:function(a,b){b=parseInt(b);return/[A-Z|a-z]/g.exec(a)?"string"==typeof a?QZONE.FP.getPURL(a,b):parent.DEFAULT_USER_PORTRAIT:"http://qlogo"+(a%4+1)+".store.qq.com/qzone/"+a+"/"+a+"/"+b}};
QZBlog.Logic.SpaceHostInfo={_strSignature:null,_bProcessing:!1,hasPrivatePwd:function(){return 1==QZBlog.Util.getBitMapFlag(44)},hasPrivatePwdVerified:function(){return!(""==QZFL.cookie.get("prvk")||null==QZFL.cookie.get("prvk"))},needVerifyPrivate:function(){return 1==QZBlog.Util.getBitMapFlag(45)},isAlphaUser:function(){return 1==QZBlog.Util.getBitMapFlag(58)},isFamousUser:function(){return 1==QZBlog.Util.getBitMapFlag(7)},isBizUser:function(){return 1==QZBlog.Util.getBitMapFlag(5)},isInteractiveUser:function(){return 1==
QZBlog.Util.getBitMapFlag(52)},isVipUser:function(){return 1==QZBlog.Util.getBitMapFlag(27)},getSpaceUrl:function(){return QZBlog.Util.getSpaceUrl(this.getUin())},getLoginUserSpaceUrl:function(){return QZBlog.Util.getSpaceUrl(this.getLoginUin())},getLoginUin:function(){return QZBlog.Util.getLoginUin()},isValidLoginUin:function(){return QZBlog.Logic.isInPengyou?!!QZBlog.Util.getLoginUin():1E4<QZBlog.Util.getLoginUin()},isOwnerMode:function(){return this.getLoginUin()==this.getUin()},getVipLevel:function(){var a=
parent.QZONE.dataCenter.get("yellowDiamondInfo");return a?a.level:-1},getUin:function(){return QZBlog.Util.getSpaceUin()},getNickname:function(){return QZBlog.Util.getNickname()},checkAuthorization:function(){return!!(QZBlog.Util.getBitMapFlag(11)+QZBlog.Util.getBitMapFlag(10)+QZBlog.Util.getBitMapFlag(9))},checkReplyAuthorization:function(){return!!(QZBlog.Util.getBitMapFlag(14)+QZBlog.Util.getBitMapFlag(13)+QZBlog.Util.getBitMapFlag(12))},getListViewMode:function(a){if("undefined"!=typeof parent.blogFixedViewMode)return a&&
"function"==typeof a&&a(),parent.blogFixedViewMode;if(QZBlog.Logic.SpaceHostInfo.isOwnerMode()&&parent.g_oBlogSettingInfoMgr){if(parent.g_oBlogSettingInfoMgr.isSettingInfoReady(this.getUin()))return a&&"function"==typeof a&&a(),parent.g_oBlogSettingInfoMgr.getListMode(this.getUin());a&&"function"==typeof a&&QZBlog.Util.getSubLoginBitMapFlag(function(b,d){b&&(parent.g_oBlogSettingInfoMgr.createSettingInfo(QZBlog.Logic.SpaceHostInfo.getLoginUin(),b),a())},1)}else{if(parent.QZONE.dataCenter.get("QZBlogListMode_"+
QZBlog.Logic.SpaceHostInfo.getUin()))return a&&"function"==typeof a&&a(),parent.QZONE.dataCenter.get("QZBlogListMode_"+QZBlog.Logic.SpaceHostInfo.getUin());if(a&&"function"==typeof a){var b=new QZBlog.Util.NetRequest({url:QZBlog.CGI_URL.get("blog_get_blogbitmap"),data:{hostuin:QZBlog.Logic.SpaceHostInfo.getUin(),fupdate:1},method:"get",uniqueCGI:!0});b.onSuccess=function(b){b=b.data.hostflag.substr(0,8);b=parseInt(b,16)>>25&1;parent.QZONE.dataCenter.save("QZBlogListMode_"+QZBlog.Logic.SpaceHostInfo.getUin(),
b?parent.BlogListViewType.DIGEST:parent.BlogListViewType.CLASSIC);a()};b.send()}}return-1}};QZBlog.Logic.jumpToBaseListCGIUrl=function(){location.href="http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V6_PATH+"/bloglist.html"};QZBlog.Logic.jumpToList=function(a){QZBlog.Router.redirectTo("bloglist","catalog="+(a||""))};parent.g_nBlogFirstPageRandSeed||(parent.g_nBlogFirstPageRandSeed=Math.random());
QZBlog.Util.ImageManager={_nCleanTime:18E4,_imgArr:[],_bCleaning:!1,PRELOAD_URLS:["/ac/b.gif",DEFAULT_PORTRAIT_IMGURL,LOADING_GIF],_removeImage:function(a){return this._imgArr[a]?(delete this._imgArr[a],this._imgArr[a]=null,!0):!1},loadObjectImage:function(a,b,c){b&&b.tagName&&"img"==b.tagName.toLowerCase()&&this.loadImage(a,!0,function(){b.src=a;c&&c()})},loadImage:function(a,b,c){if(a)if(!0==this._bCleaning){var d=200;this._imgArr[a]&&(d=Math.max(parseInt(this._imgArr[a].getAttribute("timeout"),
10)-50,0),this._imgArr[a].setAttribute("timeout",d));setTimeout(QZONE.event.bind(this,this.loadImage,a,b,c),d)}else!1!=b&&(b=!0),this._imgArr[a]?1==this._imgArr[a].getAttribute("loaded")&&c?c():null==this._imgArr[a].getAttribute("loaded")&&(d=Math.max(parseInt(this._imgArr[a].getAttribute("timeout"),10)-100,0),this._imgArr[a].setAttribute("timeout",d),setTimeout(QZONE.event.bind(this,this.loadImage,a,b,c),d)):(d=new Image,d.setAttribute("removeable",b),d.onload=function(){this.onerror=this.onload=
null;this.setAttribute("loaded",1);c&&c()},d.onerror=function(){this.onerror=this.onload=null;this.setAttribute("loaded",0)},this._imgArr[a]=d,this._imgArr[a].src=a,this._imgArr[a].setAttribute("timeout",500))},_initMgr:function(){for(var a in this.PRELOAD_URLS)this.loadImage(this.PRELOAD_URLS[a],!1,null);setInterval(QZONE.event.bind(this,function(){this._bCleaning=!0;for(var a in this._imgArr)this._imgArr[a]&&"undefined"!=typeof this._imgArr[a].getAttribute("loaded")&&!1!=this._imgArr[a].getAttribute("removeable")&&
!1==this._removeImage(this._imgArr.src)&&console.log("\u65e0\u6cd5\u5220\u9664QZBlog.Util.ImageManager\u7684\u7f13\u5b58\uff1a"+this._imgArr.src);this._bCleaning=!1}),this._nCleanTime)}()};QZBlog.Util.scaleRegion=function(a,b,c,d){if(!a||!b)return null;var e,f,g=!0;c&&d&&a>c&&b>d?a/b>c/d?(f=c*b/a,e=c):(e=d*a/b,f=d):c&&a>c?(f=c*b/a,e=c):d&&b>d?(e=d*a/b,f=d):g=!1;return g?{width:e,height:f}:null};
QZBlog.Util.adjustImageSize=function(a,b,c,d,e){var f=new Image;f.onload=function(){var g=a.style.width?parseInt(a.style.width,10):a.width,h=a.style.height?parseInt(a.style.height,10):a.height,k=f.width,l=f.height;if(g=QZBlog.Util.scaleRegion(g||k,h||l,b,c))a.style.width=parseInt(g.width,10)+"px",a.style.height=parseInt(g.height,10)+"px",e&&(a.style.cursor="pointer",a.title="\u70b9\u51fb\u9884\u89c8\u539f\u56fe",a.onclick=function(){window.open(a.src)});d&&d(g)};f.src=a.src};
QZBlog.Util.createTemplate=function(){if($("xmpTemplate")){for(var a=QZONE.userAgent.opera?$("xmpTemplate").innerText:$("xmpTemplate").innerHTML,b=/\{(\w+)\x20begin\}((.|\n|\r)+?)\{end\}/ig,c;null!=(c=b.exec(a));)3>c.length||(parent.g_hsBlogTemplate[c[1]]=c[2]);$("xmpTemplate").innerHTML=$("xmpTemplate").innerText=""}};"undefined"==typeof parent.g_hsBlogTemplate&&(parent.g_hsBlogTemplate={});
QZBlog.Logic.TCISDClick=function(){var a={"/BlogList":"BlogList","/BlogEditer":"BlogEditer","/BlogContent":"BlogContent","/formatdiary":"formatdiary"};return function(b,c,d,e){if(!QZBlog.Logic.isInPengyou&&c){b=a[c]?a[c]+"."+b:b;d=d||"blog.qzone.qq.com";console.log("TCISD:",b,d,c);try{QZONE.FP._t.TCISD.hotClick(b,d,c)}catch(f){console.log(f)}}}}();
QZBlog.Logic.TCISDClick.batchBind=function(a,b){b=QZFL.object.extend({eventType:"mousedown",url:null,domain:null,container:document},b||{});if(!b.url)throw"TCISDClick URL REQUIRED";var c={};QZFL.each(a,function(a,e){c[e]=function(){QZBlog.Logic.TCISDClick(a,b.url,b.domain)}});QZBlog.Logic.batchDelegate(c,b.container,b.eventType,!0)};
QZBlog.Logic.batchDelegate=function(){var a=function(a,c){var d;$e(c).each(function(c){if(!d&&(c==a||QZFL.dom.isAncestor(c,a)))return d=c,!1});return d};return function(b,c,d,e){d=d||"click";c=c||document;QZFL.each(b,function(b,g){QZFL.event.delegate(c,g,d,function(c){var k=QZFL.event.getButton(c),l=QZFL.event.getTarget(c);!(l=a(l,g))||"click"==d&&0!=k&&l&&"A"==l.tagName&&0==(l.href||"").indexOf("http://")||(b(l),"A"!=l.tagName||e||QZFL.event.preventDefault(c))})})}}();
QZBlog.Util.Statistic=function(){var a=[],b={},c={showlist:"/index/blog/list.php",readblog:"/index/blog/show.php",neweditblog:"/index/blog/post.php",editblog:"/index/blog/edit.php",showprivatelist:"/index/blog/secret.php",readprivateblog:"/index/blog/secretshow.php",showdraftlist:"/index/blog/draft.php",editdraft:"/index/blog/editdraft.php",previewblog:"/index/blog/dopreview.php"},d=function(b,c){for(var d=null,e=-1,l=0;l<a.length;++l)if(a[l].ready){a[l].ready=!1;d=a[l];e=l;break}0>e&&(e=a.length,
d=a[a.length]=new Image,d.ready=!1);d.onload=d.onerror=function(){d.onload=null;d.onerror=null;d.ready=!0;if(5<a.length)for(var b=a.length-1;0<=b;){if(a[b].ready){delete a[b];a=a.slice(0,b).concat(a.slice(b+1));break}--b}};c?setTimeout(function(){d.src=b},c):d.src=b},e=function(a,c){return"number"==typeof a&&1<=a?(b[a]=c||(new Date).getTime(),!0):!1};return{sendPV:function(a,b){if("rizhi.qzone.qq.com"!=b||50==Math.ceil(100*Math.random())){var e="",e=b?b:QZBlog.Logic.SpaceHostInfo.isBizUser()?"biz.qzone.qq.com":
QZBlog.Logic.SpaceHostInfo.isFamousUser()?"star.qzone.qq.com":"blog.qzone.qq.com";QZBlog.Logic.isInPengyou&&(e="xiaoyou.qq.com");QZBlog.Logic.isInPengyou&&c[a]&&(a=c[a]);var e=["dm="+e,"url=/"+encodeURIComponent(a)],k=document.referrer.match(/https?:\/\/(\w+(\.\w+)+)(\/[^?#]*)?/);if(k){var l="";if(1<k.length){var m=k[1],n=m.match(/(\d{5,10})\.(\w+(\.\w+)+)(\/[^?#]*)?/);n&&(m="user.qzone.qq.com",l=n[1]);e.push("rdm="+m)}3<k.length&&e.push("rurl="+encodeURIComponent((0<l.length?"/"+l:"")+k[3]))}k=QZONE.cookie.get("pvid");
k||(k=Math.round(2147483647*Math.random())*(new Date).getUTCMilliseconds()%1E10,QZONE.cookie.set("pvid",k,31104E7,"qq.com"));e.push("pvid="+k);d("http://pingfore.qq.com/pingd?scr=-&scl=-&lang=-&java=1&cc=-&pf=-&tz=-8&ct=-&vs=3.3&tt=-&"+e.join("&")+"&sds="+Math.random(),1E3);console.log("sendPV:",a,":",b)}},sendUPV:function(){QZBlog.Logic.SpaceHostInfo.isFamousUser()?d("http://p1.qzone.qq.com/fcg-bin/fcg_page_pu_view?id="+QZBlog.Logic.SpaceHostInfo.getUin()+"&type=2&info=2%2C0&r="+Math.random(),1E3):
QZBlog.Logic.SpaceHostInfo.isBizUser()&&d("http://p1.qzone.qq.com/fcg-bin/fcg_page_pu_view?id="+QZBlog.Logic.SpaceHostInfo.getUin()+"&type=1&info=2%2C0&r="+Math.random(),1E3)},sendSpeedStat:function(a,b,c){if(b&&c){b="http://isdspeed.qq.com/cgi-bin/r.cgi?flag1=175&flag2="+b+"&flag3="+c+"&flag4=0&flag5=0&uin="+QZBlog.Logic.SpaceHostInfo.getUin()+"&hh="+Math.random();c=0;for(var e=a.length;c<e;c++)b+="&"+(c+1)+"="+(a[c]-a[0]);d(b)}else console.log("\u9700\u8981\u6307\u5b9a\u6d4b\u901f\u9875\u9762\uff0c\u548c\u6d4b\u901f\u9879id")},
addSpeedPoint:e,resetSpeedPoint:function(){window.blogSpeedBasePoint=(new Date).getTime();b=[]},sendSpeedStatistic:function(a,c,h){if(6!=c&&50!=Math.ceil(100*Math.random()))return parent.bcSpeedBasePoint=null,parent.blSpeedBasePoint=null,!1;if(!window.blogSpeedBasePoint)return!1;var k=window.blogSpeedBasePoint;if(7==c){if(!parent.bcSpeedBasePoint)return!1;k=(new Date(parent.bcSpeedBasePoint)).getTime()}e(1,k);a="http://isdspeed.qq.com/cgi-bin/r.cgi?flag1=175&flag2="+a+"&flag3="+c+"&flag4=0&flag5=0&uin="+
QZBlog.Logic.SpaceHostInfo.getUin()+"&hh="+Math.random();for(var l in b)b[l]&&(a+="&"+l+"="+(b[l]-k));console.log("SpeedStat:",a);h=void 0==h?1E3:parseInt(h,10)||0;return d(a,h)},sendRetCodeStatic:function(a){a=QZFL.object.extend({domain:null,cgiName:null,code:null,type:0==a.code?1:2,time:0,rate:1,uin:QZBlog.Logic.SpaceHostInfo.getLoginUin()},a);a.cgiName=URIencode(a.cgiName);var b="http://c.isdspeed.qq.com/code.cgi?",c="",e;for(e in a)null!==a[e]&&(b+=c+e+"="+a[e],c="&");console.log("RC4.0:",b);
parent.QZFL.pingSender?parent.QZFL.pingSender(b,1E3):d(b,1E3)}}}();QZBlog.Util.getToken=function(){return QZONE.FP.getACSRFToken()};QZBlog.Util.getCurrentAppWindow=function(){return QZONE.FP.getCurrentAppWindow()||(frameElement?null:parent)};QZBlog.Util.getBitMapFlag=function(a){return QZONE.FP.getBitMapFlag(a)};QZBlog.Util.setBitMapFlag=function(a,b){QZONE.FP.setBitMapFlag(a,b)};QZBlog.Util.getLoginBitMap=function(a){return QZONE.FP.getLoginBitmap(a)};QZBlog.Util.getNickname=function(){return QZONE.FP.getNickname()};
QZBlog.Util.getSpaceUin=function(){return QZONE.FP.getQzoneConfig().ownerUin};QZBlog.Util.getPengyouDecodeUin=function(){return QZONE.FP._t.CUSER?QZONE.FP._t.CUSER.get("qq"):""};QZBlog.Util.getLoginUin=function(){return QZONE.FP.getQzoneConfig().loginUin};QZBlog.Util.getStyleID=function(){return QZONE.FP.getQzoneConfig().styleId};QZBlog.Util.isOldXWMode=function(){var a=!1;try{a=!!QZONE.FP._t.QZONE.dressDataCenter.isOldXWMode()}catch(b){}return a};QZBlog.Util.isSmallMode=function(){return!QZONE.FP.getQzoneConfig().full};
QZBlog.Util.isWideMode=function(){return parent.g_bFromInfoCenter?!1:QZONE.FP.getQzoneConfig().wide};QZBlog.Util.getSpaceMode=function(){return QZBlog.Util.isFreeMode()?5:parent.g_Izone?6:parent.g_bFromInfoCenter?4:QZBlog.Util.isWideMode()?1:QZBlog.Util.isSmallMode()?3:2};QZBlog.Util.isFreeMode=function(){return!!parent.g_OFPLite};QZBlog.Util.isLiteMode=function(){return QZONE.FP.getQzoneConfig().isLite};
QZBlog.Util.getFreeModeMaxMediaWidth=function(){return QZBlog.Util.isFreeMode()?Math.max(0,QZBlog.Util.getFrameWidth()-20):-1};QZBlog.Util.getFrameWidth=function(){var a=window.frameElement||parent.document.getElementById(FRAME_ID)||parent.document.getElementById(MSG_FRAME_ID);return QZONE.dom.getPosition(a).width};QZBlog.Util.getFrameHeight=function(){var a=window.frameElement||parent.document.getElementById(FRAME_ID)||parent.document.getElementById(MSG_FRAME_ID);return QZONE.dom.getPosition(a).height};
QZBlog.Util.showLoginBox=function(a,b,c){QZONE.FP.showLoginBox(a,b,"",{mode:!!c})};QZBlog.Util.hideMsgbox=function(){QZONE.FP.hideMsgbox()};QZBlog.Util.showMsgbox=function(a,b,c){1==b&&(b=5);parent.QZONE.FP.showMsgbox(a,b,c)};QZBlog.Util.appendPopupFn=function(a){QZONE.FP.appendPopupFn(a)};QZBlog.Util.popupDialog=function(a,b,c,d){QZONE.FP.popupDialog(a,b,c,d)};QZBlog.Util.closePopup=function(){QZONE.FP.closePopup()};QZBlog.Util.setScrollTop=function(a){QZONE.FP.setScrollTop(a)};
QZBlog.Util.getScrollTop=function(){return QZONE.FP.getScrollTop()};QZBlog.Util.toApp=function(a){QZONE.FP.toApp(a)};QZBlog.Util.getPortraitList=function(a,b){return QZONE.FP.getPortraitList(a,b,{size:100,needScore:1})};QZBlog.Util.regClickStream=function(a,b){};QZBlog.Util.getLoginUserBitMap=function(a,b){QZBlog.Logic.SpaceHostInfo.isValidLoginUin()&&QZONE.FP.getLoginUserBitMap(a,b)};
QZBlog.Util.jsonToString=function(a){switch(typeof a){case "string":return'"'+a.replace(/(["\\])/g,"\\$1")+'"';case "array":return"["+a.map(QZBlog.Util.jsonToString).join(",")+"]";case "object":if(a instanceof Array){for(var b=[],c=a.length,d=0;d<c;d++)b.push(QZBlog.Util.jsonToString(a[d]));return"["+b.join(",")+"]"}if(null===a)return"null";b=[];for(c in a)b.push(QZBlog.Util.jsonToString(c)+":"+QZBlog.Util.jsonToString(a[c]));return"{"+b.join(",")+"}";case "number":return a;case !0:case !1:return a}};
QZBlog.Util.getLoginVIPLevel=function(){return QZONE.FP.getLoginBitmap(18,4)};QZBlog.Util.getLoginIsVIP=function(){return QZONE.FP.getLoginBitmap(27)};QZBlog.Util.isLoginVIPExpress=function(){return QZONE.FP.getLoginBitmap(17)};QZBlog.Util.getSubLoginBitMapFlag=function(a,b){QZBlog.Logic.SpaceHostInfo.isValidLoginUin()&&QZONE.FP.getSecondaryBitMapFlag(a,b,null,QZBlog.Logic.SpaceHostInfo.getLoginUin())};QZBlog.Util.CreditLevel={A:0,B_FIRST:1,B_SECOND:2,B_THIRD:3,C_FIRST:4,C_SECOND:5,C_THIRD:6,D:7};
QZBlog.Util.getLoginUserCreditLevel=function(){var a=QZONE.FP.getCrediteLevel(QZBlog.Logic.SpaceHostInfo.isOwnerMode()?!0:!1);switch(a){case 0:a=QZBlog.Util.CreditLevel.B_THIRD;break;case 1:a=QZBlog.Util.CreditLevel.A;break;case 2:a=QZBlog.Util.CreditLevel.B_FIRST;break;case 3:a=QZBlog.Util.CreditLevel.B_SECOND;break;case 4:a=QZBlog.Util.CreditLevel.C_FIRST;break;case 5:a=QZBlog.Util.CreditLevel.C_SECOND;break;case 6:a=QZBlog.Util.CreditLevel.C_THIRD;break;case 7:a=QZBlog.Util.CreditLevel.D}return a};
QZBlog.Util.getCurrentSpaceUserCreditLevel=function(){var a=QZONE.FP.getCrediteLevel(!1);switch(a){case 0:a=QZBlog.Util.CreditLevel.B_THIRD;break;case 1:a=QZBlog.Util.CreditLevel.A;break;case 2:a=QZBlog.Util.CreditLevel.B_FIRST;break;case 3:a=QZBlog.Util.CreditLevel.B_SECOND;break;case 4:a=QZBlog.Util.CreditLevel.C_FIRST;break;case 5:a=QZBlog.Util.CreditLevel.C_SECOND;break;case 6:a=QZBlog.Util.CreditLevel.C_THIRD;break;case 7:a=QZBlog.Util.CreditLevel.D}return a};
QZBlog.Util.getSecureSettingInfo=function(a,b){var c=this;if(c._oSecureInfo)"function"==typeof b&&(c._hsKeyWords={writeBlogEntry:"block_write_blog",writeBlogError:"disable_button_on_fail",writeBlogHint:"suggest_save_on_write",forbidCommentAndReply:"block_comment_and_reply",disable_read_counter:"disable_read_counter"},b(c._oSecureInfo[c._hsKeyWords[a]]));else if(1<=c._nSecureCalledCnt)"function"==typeof b&&b(0);else{c._nSecureCalledCnt=c._nSecureCalledCnt?c._nSecureCalledCnt+1:1;var d=new QZBlog.Util.NetRequest({url:QZBlog.CGI_URL.get("blog_get_rz_setting"),
data:{uin:QZBlog.Logic.SpaceHostInfo.getUin(),fupdate:1},method:"get",uniqueCGI:!0,isSilenderMode:!0});d.onSuccess=function(d){c._oSecureInfo=d.data.web_sec;c.getSecureSettingInfo(a,b)};d.onError=function(){"function"==typeof b&&b(0)};d.send()}};
QZBlog.Util.getSignature=function(a,b){if(void 0!==parent.spaceOwnerSignature)b(parent.spaceOwnerSignature);else{var c=new QZBlog.Util.NetRequest({url:"http://"+SPACE_MAIN_READ_DOMAIN+"/cgi-bin/user/cgi_get_signature",data:{huin:a||QZBlog.Logic.SpaceHostInfo.getUin(),fuin:QZBlog.Logic.SpaceHostInfo.getLoginUin(),notubb:1,fupdate:1},method:"get",uniqueCGI:!0,isSilenderMode:!0});c.onSuccess=function(a){0==a.code&&(parent.spaceOwnerSignature=a.data.sign,b(a.data.sign))};c.send()}};
QZBlog.Util.VerifycodeType={NEEDCODE:0,ERRCODE:1,IPC_CHECK:2,NORMALCODE:3};QZBlog.Util.MSG_LIFTTIME={HIGH:3E3,MIDDLE:1500,LOW:1E3,INFINITE:0};QZBlog.Util.DumpMsgFunc=function(){QZBlog.Util.showMsgbox("\u670d\u52a1\u5668\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u5019\u91cd\u8bd5",1,QZBlog.Util.MSG_LIFTTIME.MIDDLE)};QZBlog.Util.showSpaceCloseHintDlg=function(){QZBlog.Util.popupDialog("\u6e29\u99a8\u63d0\u793a",{src:"/qzone/newblog/v5/dialog/space_close_hint.html"},360,110)};
QZBlog.Util.showVerifycodeDlg=function(a,b){var c='<iframe frameborder="no" id="verifycodeFrame" style="width:100%;height:160px;" src="/qzone/verifycode.html?imgcode='+BLOG_VERIFY_CODE+"&type="+a+'"></iframe>';try{QZONE.FP.popupDialog._cpp&&QZBlog.Util.closePopup()}catch(d){}parent.window.setTimeout(function(){parent.popupCallback=function(a){a&&b(a)};QZONE.FP.popupDialog("\u8bf7\u8f93\u5165\u9a8c\u8bc1\u7801",c,270,160)},300)};
QZBlog.Util.addDataToUri=function(a,b,c,d){d=d?d.toLowerCase():"get";var e=RegExp("([&|?]"+a+"=)([^&]*)");if(e.test(c))return c.replace(e,function(a,c){return c+b});d="post"==d?"&":0<=c.indexOf("?")?"&":"?";return c+d+a+"="+b};
QZBlog.Util.BlogNetProcessor=function(){this._DEFAULT_TYPE="get";this._DEFAULT_CHARSET="GB2312";this._DEFAULT_CALLBACK_NAME="_Callback";this._DEFAULT_POSTTYPE="XML";this.pwdHandler=this.spaceCloseHandler=this.confirmHandler=this.alertHandler=this.forbiddenHandler=this.rightHandler=this.loginHandler=this.verifyHandler=null;this._bProcessing=!1;this._nProcessingTimer=-1;this._type=this._DEFAULT_TYPE;this._url="";this._charset=this._DEFAULT_CHARSET;this._silentMode=!0;this._errHandler=this._succHandler=
QZONE.emptyFn;this._callbackName=this._DEFAULT_CALLBACK_NAME;this._postType=this._DEFAULT_POSTTYPE;this._nStartTime=null;this._defaultErrHandler=function(){this._silentMode||QZBlog.Util.DumpMsgFunc();this._errHandler&&this._errHandler();var a=(new Date).getTime()-this._nStartTime;this.sendStatCode(this._url,"network error",a);this.close()};this.sendStatCode=function(a,b,c){var d=function(){try{stat_send_retcode(a,b,c)}catch(d){}};"function"!=typeof stat_send_retcode?QZFL.imports("http://"+IMGCACHE_DOMAIN+
IMGCACHE_BLOG_V5_PATH+"/script/retcode_stat.js",d,"utf-8"):d()};this._commonErrTypeHandler=function(a,b){switch(a){case "pwd2 expired":if(QZBlog.Util.clearPwd2Sig(),this.pwdHandler){this.pwdHandler();break}case "login":case "not login":if(this.loginHandler){this.loginHandler();break}case "ipc_check":if(this.verifyHandler){QZBlog.Util.showVerifycodeDlg(QZBlog.Util.VerifycodeType.IPC_CHECK,QZONE.event.bind(this,this.verifyHandler));break}case "verify code":if(this.verifyHandler){QZBlog.Util.showVerifycodeDlg(QZBlog.Util.VerifycodeType.ERRCODE,
QZONE.event.bind(this,this.verifyHandler));break}case "verify":case "need_verify":if(this.verifyHandler){QZBlog.Util.showVerifycodeDlg(QZBlog.Util.VerifycodeType.NEEDCODE,QZONE.event.bind(this,this.verifyHandler));break}case "alert":if(this.alertHandler){this.alertHandler(b);break}case "confirm":if(this.confirmHandler){this.confirmHandler(b);break}case "forbidden":if(this.forbiddenHandler){this.forbiddenHandler();break}case "spaceclose":if(this.spaceCloseHandler){this.spaceCloseHandler();break}default:this._silentMode||
(b?QZBlog.Util.showMsgbox(b,1,QZBlog.Util.MSG_LIFTTIME.MIDDLE):QZBlog.Util.DumpMsgFunc())}};this._simpleXMLErrHandler=function(a){(a=XMLselectSingleNode(a,"/error"))&&this._commonErrTypeHandler(a.getAttribute("type"),getXMLNodeText(a))};this._simpleJsonErrHandler=function(a){a.error&&this._commonErrTypeHandler(a.error.type,a.error.msg)};this._callback=function(a){this._silentMode||QZBlog.Util.hideMsgbox();if(a){var b=(new Date).getTime()-this._nStartTime,c="";if(isXMLDoc(a)&&XMLselectSingleNode(a,
"/error"))c=XMLselectSingleNode(a,"/error").getAttribute("type"),this._simpleXMLErrHandler(a),this._errHandler&&this._errHandler.apply(null,arguments);else if(a.error)c=a.error.type,this._simpleJsonErrHandler(a),this._errHandler&&this._errHandler.apply(null,arguments);else{for(var c="success",d="blog_add blog_del_data blog_modify blog_set_top blog_modify_right blog_add_category blog_batch_modify_category blog_batch_modify_right draft_add_blog draft_modify_blog privateblog_pub2prv privateblog_prv2pub notepad_np2blog recyclebin_recover_blog".split(" "),
e=0;e<d.length;++e)if(-1!=this._url.indexOf(d[e])){QZONE.FP._t.BLOG_DISPATCH_FLAG=1;QZONE.FP._t.setTimeout("QZONE.FP._t.BLOG_DISPATCH_FLAG = 0;",3E5);break}this._succHandler&&(8==QZONE.userAgent.ie?(this._tmpHandler=this._succHandler,setTimeout(QZONE.event.bind(window,function(a,b){a._tmpHandler.apply(null,b);a._tmpHandler=QZONE.emptyFn},this,arguments),0)):this._succHandler.apply(null,arguments))}this.sendStatCode(this._url,c,b)}else QZBlog.Util.showMsgbox("\u6682\u65f6\u65e0\u6cd5\u83b7\u53d6\u670d\u52a1\u5668\u6570\u636e",
1,QZBlog.Util.MSG_LIFTTIME.MIDDLE)};this.create=function(a,b,c,d,e,f,g){if(this._bProcessing)return this._silentMode||QZBlog.Util.showMsgbox("\u6b63\u5728\u54cd\u5e94\u60a8\u7684\u64cd\u4f5c,\u8bf7\u7a0d\u5019...",6,QZBlog.Util.MSG_LIFTTIME.MIDDLE),this._nProcessingTimer=setTimeout(QZONE.event.bind(this,function(){this._bProcessing=!1}),5E3),null;clearTimeout(this._nProcessingTimer);this._url=a;this._type="post"==b?b:this._DEFAULT_TYPE;this._charset=e?e:this._DEFAULT_CHARSET;this._silentMode=!!f;
this._callbackName=g?g:this._DEFAULT_CALLBACK_NAME;this._postType=this._DEFAULT_POSTTYPE;c&&(this._succHandler=c);d&&(this._errHandler=d);this._bProcessing=!0;this.spaceCloseHandler=this.confirmHandler=this.alertHandler=this.rightHandler=this.forbiddenHandler=this.pwdHandler=this.loginHandler=this.verifyHandler=null;return this};this.setPostType=function(a){this._postType=a};this._preProcURL=function(a,b,c){-1!=a.indexOf(CGI_BLOG_R_DOMAIN)&&QZONE.FP._t.BLOG_DISPATCH_FLAG&&(a=a.replace(CGI_BLOG_R_DOMAIN,
CGI_BLOG_DOMAIN));b&&(a=QZBlog.Util.addDataToUri("g_tk",QZBlog.Util.getToken(),a));c&&(a=QZBlog.Util.addDataToUri("ref",QZBlog.Logic.isInPengyou?"qqcampus":"qzone",a));if(/\/blog_add/i.test(a)||/\/blog_modify/i.test(a)||/\/ugcblog_add/i.test(a)||/\/add_comment/i.test(a)||/\/blog_quote/i.test(a))b="28Q1206"+QZBlog.Logic.SpaceHostInfo.getLoginUin()+"_"+QZBlog.Util.getSpaceUin(),a=QZBlog.Util.addDataToUri("secverifykey",b,a);return a};this.excute=this.execute=function(){this._silentMode||QZBlog.Util.showMsgbox("\u6b63\u5728\u63d0\u4ea4\u60a8\u7684\u8bf7\u6c42\uff0c\u8bf7\u7a0d\u5019...",
6);this._nStartTime=(new Date).getTime();if("get"==this._type){var a=new QZONE.JSONGetter(this._preProcURL(this._url,!0,!0),void 0,null,this._charset);a.onSuccess=QZONE.lang.chain(QZONE.event.bind(this,this._callback),QZONE.event.bind(this,this.close));a.onError=QZONE.event.bind(this,this._defaultErrHandler);a.send(this._callbackName)}else if("post"==this._type){this._url=this._preProcURL(this._url,!0,!0);var b=new QZFL.util.URI(this._url),a=this._url.replace(b.search,""),b=b.search.substring(1);
this._postType==this._DEFAULT_POSTTYPE?(a=this._preProcURL(a,!0,!0),loadXMLAsync("tmpBlogXMLRequest",a,QZONE.event.bind(this,function(){try{this._callback(parent.g_XDoc.tmpBlogXMLRequest),delete parent.g_XDoc.tmpBlogXMLRequest,parent.g_XDoc.tmpBlogXMLRequest=null}catch(a){}this.close()}),QZONE.event.bind(this,this._defaultErrHandler),!0,b)):(a=this._preProcURL(a,!1,!0),a=new QZONE.FormSender(a,"post",b,this._charset),a.onSuccess=QZONE.event.bind(this,function(a){try{this._callback(a)}catch(b){}this.close()}),
a.onError=QZONE.event.bind(this,this._defaultErrHandler),a.send())}else return!1;return!0};this.close=function(){this._bProcessing=!1;this._type=this._DEFAULT_TYPE;this._url="";this._charset=this._DEFAULT_CHARSET;this._silentMode=!1;this._errHandler=this._succHandler=QZONE.emptyFn;this._callbackName=this._DEFAULT_CALLBACK_NAME;this.confirmHandler=this.alertHandler=this.rightHandler=this.forbiddenHandler=this.pwdHandler=this.loginHandler=this.verifyHandler=null};return this};
QZBlog.Util.NetProcessor=new QZBlog.Util.BlogNetProcessor;
(function(a){function b(a){this.startTimeStamp=(new Date).getTime();this.config=QZFL.object.extend({url:null,data:{},method:"get",charset:"gbk",callbackName:"_Callback",timeout:3E4,maxRequestInterval:500,useFlashMode:!1,useTopQZFL:!1,isSilenderMode:void 0,startMsgTimeout:1500},a);this.guid="NET_REQUEST_"+ ++d;this._startMsgTm=null;if("function"==typeof this.config.data)this.config.datagetter=this.config.data,this.config.data=this.config.datagetter();else{var b=this;this.config.datagetter=function(){return b.config.data}}this.config.method=
this.config.method.toLowerCase();if(!this.config.url||"get"!=this.config.method&&"post"!=this.config.method||"get"==this.config.method&&!this.config.callbackName)throw"NetRequest Parameters Error";void 0==this.config.isSilenderMode&&(this.config.isSilenderMode="post"!=this.config.method)}var c,d=0,e={},f=[],g=[],h={"-3000":"NO_LOGIN","-4001":"NO_LOGIN","-4002":"NO_LOGIN","-3001":"VERIFYCODE_REQUIRED","-4006":"VERIFYCODE_REQUIRED","-3002":"VERIFYCODE_ERROR","-4008":"VERIFYCODE_ERROR","-4007":"VERIFYCODE_IPC_CHECK",
"-4017":"TOBEAUDITED","-4015":"MSG_FORBIDDEN","-50000":"NEED_PWD2","-49999":"NEED_PWD2","-49998":"NEED_PWD2"};b.prototype.onStart=function(){this.config.isSilenderMode||(this._startMsgTm=setTimeout(function(){QZBlog.Util.showMsgbox("\u6b63\u5728\u54cd\u5e94\u60a8\u7684\u64cd\u4f5c,\u8bf7\u7a0d\u5019...",6)},this.config.startMsgTimeout))};b.prototype.onSuccess=function(a){if(!this.config.isSilenderMode){var b;try{b=a.data.message}catch(c){}QZBlog.Util.showMsgbox(b||"\u64cd\u4f5c\u6210\u529f",4)}};
b.prototype.onError=function(a,b){this.config.isSilenderMode||(a=a+'<span style="color:#ddd; position:absolute">'+(b&&b.code?b.code:"")+"</span>",QZBlog.Util.showMsgbox(a,1,QZBlog.Util.MSG_LIFTTIME.MIDDLE))};b.prototype.onTimeout=function(){this.onError("\u7531\u4e8e\u60a8\u7684\u7f51\u7edc\u6bd4\u8f83\u6162\uff0c\u8bf7\u7a0d\u5019\u518d\u8bd5")};b.prototype.onResponse=function(a){this.config.isSilenderMode||QZBlog.Util.hideMsgbox();if(!a||"undefined"==typeof a.code)return this.onError("\u6682\u65f6\u65e0\u6cd5\u83b7\u53d6\u670d\u52a1\u5668\u6570\u636e",
a);var b=a.message||"\u60a8\u7684\u64cd\u4f5c\u6682\u65f6\u65e0\u6cd5\u8fdb\u884c\uff0c\u8bf7\u5237\u65b0\u9875\u9762\u540e\u91cd\u65b0\u5c1d\u8bd5";if(0==a.code)this.onSuccess(a);else if(h[a.code])switch(h[a.code]){case "NO_LOGIN":this.loginHandler();break;case "NEED_PWD2":this.pwd2Handler();break;case "VERIFYCODE_REQUIRED":this.verifyHandler(QZBlog.Util.VerifycodeType.NORMALCODE);break;case "VERIFYCODE_IPC_CHECK":this.verifyHandler(QZBlog.Util.VerifycodeType.IPC_CHECK);break;case "VERIFYCODE_ERROR":this.verifyHandler(QZBlog.Util.VerifycodeType.ERRCODE);
break;case "MSG_FORBIDDEN":this.msgForbiddenHandler(a);break;case "TOBEAUDITED":this.auditHandler(a);break;default:this.onError(b,a)}else this.onError(b,a)};b.prototype.msgForbiddenHandler=function(a){if(QZONE.FP.showGagMsg)QZONE.FP.showGagMsg();else this.onError(a.message,a)};b.prototype.auditHandler=function(a){QZBlog.Util.showMsgbox(a.message||"\u63d0\u4ea4\u6210\u529f",4);this.onSuccess(a)};b.prototype.loginHandler=function(){var a=this;QZONE.FP.showLoginBox(null,function(){var b=QZBlog.Logic.SpaceHostInfo.getLoginUin();
QZFL.each(b?f:g,function(a){a(b)});b&&(a.config.data=a.config.datagetter(),a.send())})};b.prototype.verifyHandler=function(a){var b=this;QZBlog.Util.hideMsgbox();QZBlog.Util.showVerifycodeDlg(a,function(a){a=QZBlog.Util.buildParam(b.config.data,(b.config.uniqueCGI?"verifyCode":"verifycode")+"="+a);b.send(null,a)})};b.prototype.pwd2Handler=function(){var a=this;QZBlog.Util.clearPwd2Sig();QZONE.FP.closePopup();QZBlog.Util.queryPwdState(function(){var b=QZBlog.Util.buildParam(a.config.data,{pwd2sig:QZBlog.Util.getPwd2Sig()});
a.send(null,b)})};b.prototype.confirmHandler=function(a){confirm(a)&&this.send()};b.prototype._cgiStatic=function(a){var b=this.config.url,c=(new Date).getTime()-this.startTimeStamp,d=function(){try{stat_send_retcode2(b,a,c,!0)}catch(d){}};"function"!=typeof stat_send_retcode2?QZFL.imports("http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/script/retcode_stat.js",function(){d()},"utf-8"):d()};b.prototype.requestFrequent=function(){return!1};b.prototype.onFlashSenderCallback=function(a){a=a||{};if(!a.id||
a.error)this.onError(a.error||"FLASH RESPONSE FORMAT ERROR");else if(a.id==this.guid){delete FlashSenderCallback.list[this.guid];var b,c=function(a){a=a.replace(/[\s\S]*?frameElement\.callback\(/i,"").replace(/\)[\s\S]*?<\/script>[\s\S]+/g,"").replace(/\r|\n/g,"");eval("var data = "+a);return data?data:null};try{b=c(a.data),this.onResponse(b),this._cgiStatic(b?b.code:"")}catch(d){this.onError("FLASH RESPONSE FORMAT ERROR")}}};b.prototype.send=function(a,b){var d=this,f="post"==this.config.method;
this.startTimeStamp=(new Date).getTime();if(this.config.maxRequestInterval){var g=(new Date).getTime(),h=this.config.url;if(!e[h])e[h]=g;else if(g-e[h]>this.config.maxRequestInterval)e[h]=g;else if(!1===d.requestFrequent())return!1}a||(a=this.config.url.replace(/\&g_tk=(\d)*$/,"&g_tk="+QZBlog.Util.getToken()));a=a||this.config.url;b=QZBlog.Util.buildParam(b||this.config.data,{iNotice:this.config.isSilenderMode?"0":"1",inCharset:this.config.charset,outCharset:this.config.charset,format:f?"fs":"jsonp",
ref:QZBlog.Logic.isInPengyou?"qqcampus":"qzone",json:f?1:null});f&&(b=QZBlog.Util.buildParam(b,{g_tk:QZBlog.Util.getToken()}));if(/\/blog_quote/i.test(this.config.url)||/\/add_comment/i.test(this.config.url)||/\/add_blog/i.test(this.config.url)||/\/quote_blog/i.test(this.config.url)||/\/mod_blog/i.test(this.config.url)||/\/blog_add/i.test(this.config.url)||/\/blog_modify/i.test(this.config.url)||/\/ugcblog_add/i.test(this.config.url))g="28Q1206"+QZBlog.Logic.SpaceHostInfo.getLoginUin()+"_"+QZBlog.Util.getSpaceUin(),
b=QZBlog.Util.buildParam(b,{secverifykey:g});if(this.config.useFlashMode&&c)return window.FlashSenderCallback||(window.FlashSenderCallback=function(a){var b=FlashSenderCallback.list;b&&QZFL.each(b,function(b){b(a)})},window.FlashSenderCallback.list={}),window.FlashSenderCallback.list[this.guid]=function(a){d.onFlashSenderCallback(a);d.reset()},g=QZBlog.Util.mergeCgiUri(a,{r:Math.random(),g_tk:QZBlog.Util.getToken()}),g=f?g:QZBlog.Util.mergeCgiUri(g,b),c.send(this.guid,g,this.config.method,f?b:""),
this.onStart(),!0;if(f){var s=0,p=this.config.useTopQZFL?new top.QZFL.FormSender(a,this.config.method,b,this.config.charset):new QZFL.FormSender(a,this.config.method,b,this.config.charset);p.onSuccess=function(a){clearTimeout(s);d.onResponse(a);var b="data parser error";a&&"undefined"!=typeof a.code&&(b=a.code);d._cgiStatic(b);d.reset()};p.onError=function(a){clearTimeout(s);d.onError(a&&a.message?a.message:"\u670d\u52a1\u5668\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u5019\u91cd\u8bd5",a);d._cgiStatic("formsender error");
d.reset()};p.send();this.config.timeout&&(s=setTimeout(function(){d.onTimeout();p.onSuccess=p.onError=QZFL.emptyFn;d.reset()},this.config.timeout))}else{f=null;try{f=parent.$j.jsonGet}catch(r){}f?f(a,b,{cfn:this.config.callbackName,charset:this.config.charset,callback:function(a){d.onResponse(a);var b="data parser error";a&&"undefined"!=typeof a.code&&(b=a.code);d._cgiStatic(b);d.reset()},onerror:function(a){d.onError(a&&a.message?a.message:"\u670d\u52a1\u5668\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u5019\u91cd\u8bd5",
a);d._cgiStatic("json getter error");d.reset()},ontimeout:this.config.timeout||null}):(f=this.config.useTopQZFL?new top.QZFL.JSONGetter(a,void 0,b,this.config.charset):new QZFL.JSONGetter(a,void 0,b,this.config.charset),f.onSuccess=function(a){d.onResponse(a);var b="data parser error";a&&"undefined"!=typeof a.code&&(b=a.code);d._cgiStatic(b);d.reset()},f.onError=function(a){d.onError(a&&a.message?a.message:"\u670d\u52a1\u5668\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u5019\u91cd\u8bd5",a);d._cgiStatic("json getter error");
d.reset()},this.config.timeout&&(f.timeout=this.config.timeout),f.onTimeout=function(){d.onTimeout();d._cgiStatic("network error");d.reset()},f.send(this.config.callbackName))}this.onStart();return!0};b.prototype.reset=function(){clearTimeout(this._startMsgTm);var a=this.config.url;e[a]&&(e[a]=(new Date).getTime())};b.initFlashSender=function(){if(!c){var a={src:"http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/flash/Sender.swf",width:"10px",height:"10px",allowScriptAccess:"always",id:"QZONE_BLOG_FLAHS_SENDER",
name:"QZONE_BLOG_FLAHS_SENDER",wmode:"transparent"};window.FlashSenderInited=function(){c=$("QZONE_BLOG_FLAHS_SENDER");window.FlashSenderInited=null};var b=document.createElement("span");document.body.appendChild(b);b.style.cssText="display:block; width:1px; height:1px; overflow:hidden; position:absolute; bottom:0; right:0;";ua.safari?b.innerHTML=QZFL.media.getFlashHtml(a):QZFL.media.insertFlash(b,a)}};b.addLoginFailHandler=function(a){g.push(a)};b.removeLoginFailHandler=function(a){for(var b=[],
c=0,d=g.length;c<d;c++)g[c]!=a&&b.push(g[c]);g=b};b.addLoginSuccHandler=function(a){f.push(a)};b.removeLoginSuccHanlder=function(a){for(var b=[],c=0,d=f.length;c<d;c++)f[c]!=a&&b.push(f[c]);f=b};a.NetRequest=b})(QZBlog.Util);
QZBlog.Util.PaperLetterManager={cleanAllPaperStyle:function(){$("paperPicArea").style.cssText="display:none;";$("paperPicArea0").style.cssText="display:none;";$("paperPicArea1").style.cssText="position:relative;display:none;top:auto;";$("paperPicArea0").src=$("paperPicArea1").src=$("paperPicArea").src="/ac/b.gif";$("veryContent").style.cssText="padding-bottom:20px;height:auto;";$("paperTitleArea").style.cssText="";try{var a=document.styleSheets[0];a.removeRule(a.length-1);a.removeRule(a.length-1)}catch(b){}},
doPaint:function(a,b){if(!a||5<=QZBlog.Util.getSpaceMode())return!1;(4==QZBlog.Util.getSpaceMode()||QZBlog.Util.isOldXWMode())&&a.setModeType(0);var c=a.getID();a.getStyle();var d=a.getType(),e=a.getFlag(),f=a.getTitleColor(),g=a.getBGColor(),h=a.getParams();$("veryTitle")&&($("veryTitle").style.display="none");$("paperTitle").innerHTML=a.getPaperTitleHTML(b);var k=$("paperTitleArea"),l=$("blogContentTable"),m=1==d||3==d?$("paperPicArea0"):$("paperPicArea");if(k&&l&&m){m.style.display="block";$("paperTitle").style.color=
$("blogDetailDiv").style.color=f;try{var n=document.styleSheets[0];n.addRule("#blogContainer a:link","{color:"+f+";}",n.length);n.addRule("#blogContainer a:visited","{color:"+f+";}",n.length)}catch(u){}k.style.height=h[d][4]+"px";k.style.width=a.MINWIDTH-h[d][1]-h[d][3]+"px";$("paperTitle").style.paddingTop=h[d][4]/2-10+"px";$("blogContainer").style.paddingRight=a.HORI_PADDING+"px";$("blogContainer").style.paddingLeft=a.HORI_PADDING+"px";m.style.width=h[d][5]+"px";$("paperBottom").style.paddingTop=
h[d][2]+"px";$("veryContent").style.cssText="height:auto!important; min-height:"+a.MINHEIGHT+"px;";$("veryContent").style.overflowY="visible";$("veryContent").style.backgroundColor=g;2==d?$("veryContent").style.backgroundPositionX="right":4==d&&($("veryContent").style.backgroundPositionY="bottom");var w=a.getBackgroundImgUrl();QZBlog.Util.ImageManager.loadImage(w,!0,function(){setTimeout(function(){$("veryContent").style.backgroundImage="url("+w+")"},1)});switch(d){case 1:k.style.paddingTop=h[d][0]+
"px";k.style.paddingBottom=h[d][4]/2+"px";k.style.marginLeft=h[d][5]-a.HORI_PADDING+"px";m.style[QZFL.userAgent.ie?"styleFloat":"cssFloat"]="left";m.style.marginLeft=-1*a.HORI_PADDING+"px";break;case 2:k.style.marginTop=h[d][0]+"px";k.style.marginBottom=h[d][4]/2+"px";m.style[QZFL.userAgent.ie?"styleFloat":"cssFloat"]="right";m.style.marginTop=-1*(h[d][0]+1.5*h[d][4])+"px";m.style.marginRight=-1*a.HORI_PADDING+"px";break;case 3:k.style.marginLeft=(h[d][1]+h[d][3]-a.HORI_PADDING)/2+"px";k.style.marginBottom=
h[d][4]/2+"px";QZONE.userAgent.Safari?(m.style.marginLeft=-2*a.HORI_PADDING+6+"px",m.style.width=h[d][5]+a.HORI_PADDING+"px"):m.style.marginLeft=-1*a.HORI_PADDING+"px";1!=e?(m.style.display="block",m.style.width="auto"):m.style.height=h[d][6]+"px";break;case 4:k.style.marginLeft=(h[d][1]+h[d][3]-a.HORI_PADDING)/2+"px";k.style.marginBottom=h[d][4]/2+"px";k.style.marginTop=h[d][4]/2+"px";m.style.display="none";m=$("paperPicArea1");m.style.display="";m.style.width=h[d][5]+"px";1!=e?(m.style.display=
"block",m.style.width="auto"):m.style.height=h[d][6]+"px";m.style.left="0px";$("paperBottom").style.paddingTop="0px";break;case 5:m.style.display="none";k.style.marginLeft=(h[d][1]+h[d][3])/2-18+"px";k.style.marginTop="60px";k.style.marginBottom=h[d][4]/2+"px";$("blogContainer").style.overflowY="visible";f=parseInt($("blogContainer").offsetHeight,10);$("blogContainer").style.height=h[d][6]?(f>h[d][6]?f:h[d][6])+"px":"auto";$("blogContainer").style.paddingTop=h[d][4]/2+"px";$("blogContainer").style.backgroundRepeat=
"no-repeat";$("blogContainer").style.backgroundPosition="top";break;default:throw"\u9519\u8bef\u7684\u4fe1\u7eb8\u7c7b\u578b";}k.style.backgroundPosition="center";k.style.backgroundRepeat="no-repeat";var s=a.getTitleImgUrl();QZBlog.Util.ImageManager.loadImage(s,!0,function(){k.style.backgroundImage="url("+s+")"});4==d&&(m.style.bottom=l.offsetHeight-$("veryContent").offsetHeight+"px");var p=a.getDescImgUrl();QZBlog.Util.ImageManager.loadImage(p,!0,function(){if(5!=d){if(m.src=p,81177==c||93007==c)if(!QZBlog.Logic.SpaceHostInfo.getLoginUin()||
!QZBlog.Util.getLoginIsVIP()){var a=$("blogContainer");if("vipLinkButton"!=a.childNodes[0].id){var b=document.createElement("div");b.className="default_free_letter default_free_letter_"+c;b.id="vipLinkButton";a.insertBefore(b,a.firstChild);b.innerHTML='<p style="top:13px;"><span class="none">\u5c0a\u4eab\u65e0\u9650\u91cf\u7cbe\u7f8e\u4fe1\u7eb8\uff01\u7acb\u5373</span><a href="http://pay.qq.com/qzone/index.shtml?aid=freepaper.anniu" target="_blank">\u5f00\u901a\u9ec4\u94bb</a></p>'}else $("vipLinkButton").style.display=
"block"}}else $("blogContainer").style.backgroundImage="url("+p+")"});1==e&&(e=a.getFlashUrl(),l=document.createElement("span"),document.body.appendChild(l),l.innerHTML='<object type="application/x-shockwave-flash" data="'+e+'" width="'+m.style.width+'" height="'+h[d][6]+'" style="'+m.style.cssText+'" align="middle"><param name="movie" value="'+e+'" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" /><param name="play" value="true" /><param name="loop" value="true" /><param name="wmode" value="transparent" /></object></span>',
QZFL.dom.swapNode(m,l.getElementsByTagName("object")[0]),m.style.display="none");return!0}}};QZBlog.Util.formatMsg=function(a,b,c){var d=/\{([\w-]+)?\}/g;return function(a,b,c){return a.replace(d,function(a,d){return c?c(b[d],d):b[d]})}}();QZBlog.Util.isEM=function(a){return/em\/e(\d{1,3}).gif/i.test(a)};QZBlog.Util.isBlankImg=function(a){return/\/ac\/b.gif/i.test(a)};QZBlog.Util.isLoadingImg=function(a){return/qzone\/newblog\/v5\/editor\/css\/loading.gif$/i.test(a)||/aoi\/img\/icenter\/loading.gif$/i.test(a)};
QZBlog.Util.isNonsenseImg=function(a){return QZBlog.Util.isEM(a)||QZBlog.Util.isBlankImg(a)||QZBlog.Util.isLoadingImg(a)};QZBlog.Util.isQqUin=function(a){return/^\d{5,20}$/g.test(a)};QZBlog.Util.getSpaceUrl=function(a){return this.isQqUin(a)?"http://user.qzone.qq.com/"+a:"http://profile.pengyou.com/index.php?mod=profile&u="+a};QZBlog.Util.isMultipleByte=function(a){a=parseInt(a.toString(16),16);return 0>a||255<a?!0:!1};
QZBlog.Util.long2time=function(a){a=new Date(1E3*a);return[a.getFullYear(),"\u5e74",a.getMonth()+1,"\u6708",a.getDate(),"\u65e5 ",a.getHours(),"\u65f6",a.getMinutes(),"\u5206",a.getSeconds(),"\u79d2"].join("")};QZBlog.Util.long2ShortTime=function(a){a=new Date(1E3*a);var b=a.getMinutes().toString(),c=a.getSeconds().toString(),b=2>b.length?"0"+b:b,c=2>c.length?"0"+c:c;return[a.getHours(),":",b,":",c].join("")};
QZBlog.Util.long2LongTime=function(a){a=new Date(1E3*a);var b=a.getMinutes().toString(),c=a.getSeconds().toString(),d=a.getHours().toString(),b=2>b.length?"0"+b:b,c=2>c.length?"0"+c:c,d=2>d.length?"0"+d:d,e=(a.getMonth()+1).toString(),f=a.getDate().toString(),e=2>e.length?"0"+e:e,f=2>f.length?"0"+f:f;return[a.getFullYear(),"-",e,"-",f," "].join("")+[d,":",b,":",c].join("")};
QZBlog.Util.long2DateTime=function(a){if(!a)return"";a=new Date(1E3*a);return a.getMonth()+1+"\u6708"+a.getDate()+"\u65e5 "+(10>a.getHours()?" 0":" ")+a.getHours()+":"+(10>a.getMinutes()?"0":"")+a.getMinutes()};QZBlog.Util.getMonthSpanTime=function(a,b){var c=new Date(a+(12==b?1:0),12==b?0:b,1);return{start:(new Date(a,b-1,1)).getTime()/1E3,end:c.getTime()/1E3}};
QZBlog.Util.jumpTop=function(a){var b=QZONE.FP.getQzoneConfig().full?parent.document:document,b=b["CSS1Compat"!=b.compatMode||QZFL.userAgent.webkit?"body":"documentElement"];a&&window.frameElement?(a=QZFL.dom.getXY(window.frameElement),6!=QZFL.userAgent.ie||1==this.getSpaceMode()||QZBlog.Util.isOldXWMode(),b.scrollTop=a[1]-41):b.scrollTop=0};
QZBlog.Util.setPageAutoResize=function(a){if(frameElement){a=parseInt(a,10)||3E3;var b=!1,c=function(){b||frameElement.height==document.body.offsetHeight||(b=!0,setTimeout(function(){window.frameElement.height=document.body.offsetHeight;b=!1},a))};QZFL.userAgent.ie&&9>QZFL.userAgent.ie?QZFL.event.addEvent(window,"resize",c):QZFL.event.addEvent(document.body,"DOMSubtreeModified",c)}};QZBlog.Util.getBlogRDomain=function(){return QZONE.FP._t.BLOG_DISPATCH_FLAG?CGI_BLOG_DOMAIN:CGI_BLOG_R_DOMAIN};
QZBlog.Util.getRecycleUrl=function(){return"http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/recycle.html"};QZBlog.Util.getEditBlogUrl=function(a,b){return QZBlog.Util.mergeStaticUri("http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/"+(QZBlog.Logic.isInPengyou?"editor.pengyou.html":"editor.html"),a,b?"source="+b:"")};QZBlog.Util.getEditPhotoBlogUrl=function(a,b){return QZBlog.Util.mergeStaticUri("http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V6_PATH+"/photoBlogEdit.html",a,b?"source="+b:"")};
QZBlog.Util.getEditTemplateBlogUrl=function(a,b){return QZBlog.Util.mergeStaticUri("http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/"+(QZBlog.Logic.isInPengyou?"editor.pengyou.html":"editor.html"),a,b?"source="+b:"","exblogtype=2")};
QZBlog.Util.getNewBlogListUrl=function(a,b){var c=QZBlog.Util.buildParam(a,b?"source="+b:"");if(!frameElement){var d="http://"+(QZBlog.Logic.isInPengyou?"baseapp.pengyou.com":"user.qzone.qq.com")+"/"+QZBlog.Logic.SpaceHostInfo.getUin()+"/blog/";return QZBlog.Util.mergeCgiUri(d,c)}return QZBlog.Util.mergeStaticUri("http://"+IMGCACHE_DOMAIN+(QZBlog.Logic.isInPengyou?IMGCACHE_BLOG_PENGYOU_PATH:IMGCACHE_BLOG_V6_PATH)+"/bloglist.html",c)};
QZBlog.Util.buildParam=function(){var a=function(a,b,e){a=a||"";for(var f=QZFL.lang.arg2arr(arguments),g=a.split("&"),h=[],f=f.slice(1),k=0;k<f.length;k++)for(var l=0;l<g.length;l++)0==g[l].indexOf(f[k]+"=")&&h.push(g[l]);return h.join("&")},b=function(b){var d=[],e=QZBlog.Util.parseStringToObjParam(b,!1),f;for(f in e)"rc"!=f&&"rg"!=f&&d.push(f+"="+e[f]);(b=a(b,"rc","rg"))&&d.push(b);return d.join("&")};return function(){var a=QZFL.lang.arg2arr(arguments),d=[];QZFL.each(a,function(a){if(QZFL.lang.isArray(a))d.push(a.join("&"));
else if("object"==typeof a)for(var b in a){var c=a[b];"string"!=typeof c&&"number"!=typeof c||d.push(encodeURIComponent(b)+"="+encodeURIComponent(a[b]))}else"string"==typeof a&&d.push(a)});a=d.join("&").replace(/^[?|#|&]{0,1}(.*?)[?|#|&]{0,1}$/g,"$1");return b(a)}}();QZBlog.Util.mergeCgiUri=function(){var a=QZFL.lang.arg2arr(arguments),b=a[0],b=b.replace(/(.*?)[?|#|&]{0,1}$/g,"$1"),a=a.slice(1);QZFL.each(a,function(a){(a=QZBlog.Util.buildParam(a))&&(b+=(0<=b.indexOf("?")?"&":"?")+a)});return b};
QZBlog.Util.mergeStaticUri=function(){var a=QZFL.lang.arg2arr(arguments),b=a[0],a=a.slice(1);QZFL.each(a,function(a){if(a=QZBlog.Util.buildParam(a))b+=/(\?|#|&)$/.test(b)?"":/\?|#|&/.test(b)?"&":"#",b+=a});return b};QZBlog.Util.parseStringToObjParam=function(a,b){if("string"!=typeof a||!a)return{};for(var c={},d,e=a.split("&"),f=0,g=e.length;f<g;++f)d=e[f].split("="),c[d[0]]=b?decodeURIComponent(d[1]):d[1];return c};
QZBlog.Router=function(){var a=parent.imgcacheDomain,b={addblog:1,addprivateblog:1,addtemplateblog:1,addblogv5:1,addphotoblog:1,draftcontent:1,privatecontent:1,recycle:1};return{redirectTo:function(a,b,e){var f=QZFL.lang.arg2arr(arguments),g=this.getSubPageUrl.apply(this,f);e?window.open(g):setTimeout(function(){if("blogcontent"==a)try{parent.$j.config.xhrGetReqProxyEnable(g)&&QZBlog.Util.canUseDomainRevert()&&(g=QZBlog.Util._realURL2ProxyURL(g),parent.QZBlog.Util.launchProxyDetect())}catch(b){}console.log("[BLOG] redirectTo",
g);window.location.href=g},0)},getSubPageUrl:function(a,d,e){e=e||QZBlog.Logic.isSeoPage;a=a.toLowerCase();d=QZBlog.Util.buildParam(d);d=QZBlog.Util.parseStringToObjParam(d,!0);var f=d.uin||b[a]?QZBlog.Logic.SpaceHostInfo.getLoginUin():QZBlog.Logic.SpaceHostInfo.getUin(),g=QZBlog.Logic.isInPengyou?"http://baseapp.pengyou.com/":"http://user.qzone.qq.com/"+f;switch(a){case "photobloglist":case "bloglist":e=e?QZBlog.Util.mergeCgiUri(g+"/blog",d):this.patchFilePath(QZBlog.Logic.isInPengyou?"app/blog/pengyou/bloglist.html":
"app/blog/v6/bloglist.html",d);break;case "blogcontent":a=d.blogId;d.blogId=null;e=e?QZBlog.Util.mergeCgiUri(g+"/blog/"+a,d):QZBlog.Util.mergeCgiUri(QZBlog.Util.getContentCGIUrl(f,a),d);break;case "draftcontent":a=d.draftId;d.draftId=null;if(e)throw"\u8349\u7a3f\u6682\u4e0d\u652f\u6301\u65b0\u7a97\u53e3\u6253\u5f00";e=QZBlog.Util.mergeCgiUri(QZBlog.Util.getDraftContentCGIUrl(f,a),d);break;case "privatecontent":a=d.blogId;d.blogId=null;e=e?QZBlog.Util.mergeCgiUri(g+"/blog/"+a,d):QZBlog.Util.mergeCgiUri(QZBlog.Util.getPrivateContentCGIUrl(a),
d);break;case "recycle":e=e?QZBlog.Util.mergeCgiUri(g+"/blog/?catalog=recycle",d):this.patchFilePath("app/blog/bloglist.html#catalog=recycle",d);break;case "msgboard":e=e?QZBlog.Util.mergeCgiUri(g+"/msgboard",d):this.patchFilePath("msgboard/msgbcanvas.html",d);break;case "addblog":case "addprivateblog":case "addtemplateblog":"addtemplateblog"==a&&(d=QZBlog.Util.buildParam(d,"exblogtype=2"));"addprivateblog"==a&&(d=QZBlog.Util.buildParam(d,"isPrivate=1"));e=e?QZBlog.Util.mergeCgiUri(g+"/blog/add",
d):this.patchFilePath("newblog/v5/"+(QZBlog.Logic.isInPengyou?"editor.pengyou.html":"editor.html"),d);break;case "addphotoblog":e=e?QZBlog.Util.mergeCgiUri(g+"/blog/addPhoto",d):this.patchFilePath("app/blog/v6/photoBlogEdit.html",d);break;case "addgridblog":e=e?QZBlog.Util.mergeCgiUri(g+"/blog/addgrid",d):this.patchFilePath("newblog/v5/grid_editor.html",d);break;default:throw"NO ROUTER FOUND";}return e},patchFilePath:function(b,d){return QZBlog.Util.mergeStaticUri("http://"+a+"/qzone/"+b,d)}}}();
QZBlog.Util.getNewBlogListUrlData=function(a){return QZFL.object.extend({hostUin:QZBlog.Logic.SpaceHostInfo.getUin(),uin:QZBlog.Logic.SpaceHostInfo.getLoginUin()||null,blogType:0,cateName:"",cateHex:"",statYear:"",reqInfo:1,pos:0,num:15,sortType:0,absType:0,startTime:"",endTime:"",source:0,rand:Math.random(),ref:QZBlog.Logic.isInPengyou?"qqcampus":"qzone",g_tk:QZBlog.Util.getToken()},a)};
QZBlog.Util._realURL2ProxyURL=function(a){try{var b=QZFL.util.URI(a),c,d;-1!=b.host.indexOf(".qzone.qq.com")?(c=b.host.replace(".qzone.qq.com",""),d="p/"+c+b.pathname):(c=b.host.replace(".qq.com",""),d="q/"+c+b.pathname);d+=b.search;return"http://"+QZONE.FP._t.location.host+"/"+d}catch(e){return a}};QZBlog.Util._isBetaUser=function(){QZONE.FP.getQzoneConfig("ownerUin");return QZONE.FP.getQzoneConfig("isOwner")};
QZBlog.Util._isspeedup=function(){var a=parent.location.host;return-1<parent.document.cookie.indexOf("blabla=dynamic")&&/(?:^user\.(s\d\.)?|\d{5,}\.|rc\.)qzone\.qq\.com/.test(a)};QZBlog.Util.canUseDomainRevert=function(a){return QZBlog.Util._isspeedup()&&QZBlog.Util._isBetaUser()};
QZBlog.Util.getContentCGIUrl=function(a,b,c,d){if(!frameElement)return"http://"+(QZBlog.Logic.isInPengyou?"baseapp.pengyou.com":"user.qzone.qq.com")+"/"+a+"/blog/"+b+"?1=1";a={uin:a,blogid:b,styledm:STYLE_DOMAIN,imgdm:IMGCACHE_DOMAIN,bdm:CGI_BLOG_DOMAIN,mode:QZBlog.Util.isSmallMode()?0:QZBlog.Util.isWideMode()?2:1,numperpage:CONTENT_COMMENT_NUM,property:parent.g_Property,timestamp:parent.g_NowTime,dprefix:QZONE.FP._t.g_DPrefix,numperpage:CONTENT_COMMENT_NUM,blogseed:0<c?c:void 0,inCharset:"gb2312",
outCharset:"gb2312",ref:QZBlog.Logic.isInPengyou?"qqcampus":"qzone"};b=QZBlog.CGI_URL.get("blog_output_data");try{QZBlog.Util.Statistic.sendPV("userhost."+(b.match(/\/\/(.*).qzone.qq\.com/)[1]||"")),QZONE.FP._t&&"b"==QZONE.FP._t.g_BLOG_LOCATION_PREFIX&&(b=b.replace("b.qzone.qq.com","b1.qzone.qq.com"))}catch(e){b=QZBlog.CGI_URL.get("blog_output_data")}return QZBlog.Util.mergeCgiUri(b,a,d)};
QZBlog.Util.getDraftContentCGIUrl=function(a,b,c,d){a={uin:a,draftid:b,styledm:STYLE_DOMAIN,imgdm:IMGCACHE_DOMAIN,bdm:CGI_BLOG_DOMAIN,timestamp:parent.g_NowTime,g_tk:QZBlog.Util.getToken(),draftseed:0<c?c:void 0,ref:QZBlog.Logic.isInPengyou?"qqcampus":"qzone",pwd2sig:d?QZBlog.Util.getPwd2Sig():void 0};return QZBlog.Util.mergeCgiUri(QZBlog.CGI_URL.get("draft_output_data","draft"),a)};
QZBlog.Util.getEditGridBlogUrl=function(a,b){return QZBlog.Util.mergeStaticUri("http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/grid_editor.html",a,b?"source="+b:"")};
QZBlog.Util.getPrivateContentCGIUrl=function(a,b){(b=b||(QZONE.FP._t.BlogNavigator?QZONE.FP._t.BlogNavigator[a]:Math.random()))||(b=QZONE.FP._t.BlogNavigator[a]=Math.random());var c={uin:QZBlog.Logic.SpaceHostInfo.getUin(),blogid:a,pwd2sig:QZBlog.Util.getPwd2Sig(),styledm:STYLE_DOMAIN,imgdm:IMGCACHE_DOMAIN,bdm:CGI_BLOG_DOMAIN,rs:b,"private":1,ref:QZBlog.Logic.isInPengyou?"qqcampus":"qzone"};return QZBlog.Util.mergeCgiUri(QZBlog.CGI_URL.get("privateblog_output_data","private"),c)};
QZBlog.Util.getCommentCGIUrl=function(a,b,c,d,e){a={uin:a,num:c,topicId:QZBlog.Logic.SpaceHostInfo.getUin()+"_"+b,start:d,r:0<e?e:void 0};return QZBlog.Util.mergeCgiUri(QZBlog.CGI_URL.get("get_comment_list"),a)};QZBlog.Util.effectSplit=function(a){if(0>=a||isNaN(a))return[];var b=[];a=a.toString(2);for(var c=a.length,d=/^1[0]*/;0<c;)b.push((1<<c-1)+""),a=a.replace(d,""),c=a.length;return b};
QZBlog.Util.scrollToElement=function(a,b,c){b=QZBlog.Util.getCurrentAppWindow().frameElement?QZFL.dom.getPosition(QZBlog.Util.getCurrentAppWindow().frameElement).top:0;a=QZBlog.Util.isSmallMode()?QZFL.dom.getPosition(a).top:QZFL.dom.getPosition(a).top+b-30;b=QZBlog.Util.isSmallMode()?document:parent.document;b["CSS1Compat"!=b.compatMode||QZFL.userAgent.webkit?"body":"documentElement"].scrollTop=a};
QZBlog.Util.TimerManager={_timerList:[],setTimeout:function(a,b){var c=Array.prototype.slice.call(arguments,2),d=window.setTimeout(function(){a.apply(null,c)},b);this._timerList.push(d);return d},clear:function(){for(var a=0;a<this._timerList.length;++a)clearTimeout(this._timerList[a])}};QZBlog.Util.clearAllCacheData=function(){parent.BlogListNavigator.clear();parent.BlogListNavigator.removePageData();parent.g_oCateInfoMgr.clear();parent.g_oBlogInfoMgr.clearAllBlogInfo();PAGE_CACHE.clean("HostRecentBlogList")};
QZBlog.Util.PageIndexManager={init:function(a,b,c,d,e){if(!a||0==a.length||1>b||1>c||b<c)return!1;this._currentIndex=c;this._totalIndex=b;this._containerArr=a;this._callback="function"==typeof d?d:QZONE.emptyFn;this._templateHTML="undefined"!=typeof e?e:this._templateHTML;this._updatePage();this._bInitialized=!0},getCurrentIndex:function(){return this._bInitialized?this._currentIndex:-1},goPage:function(a){if(!this._bInitialized||1!=a&&-1!=a)return!1;if(-1==a&&1==this._currentIndex)return QZBlog.Util.showMsgbox("\u5f53\u524d\u9875\u5df2\u7ecf\u662f\u7b2c\u4e00\u9875!",
1,QZBlog.Util.MSG_LIFTTIME.MIDDLE),!1;if(1==a&&this._currentIndex==this._totalIndex)return QZBlog.Util.showMsgbox("\u5f53\u524d\u9875\u5df2\u7ecf\u662f\u6700\u540e\u4e00\u9875!",1,QZBlog.Util.MSG_LIFTTIME.MIDDLE),!1;this._showPage(this._currentIndex+a);return!0},goDirectPage:function(a){if(!this._bInitialized)return!1;a=parseInt(a,10);if(isNaN(a))return QZBlog.Util.showMsgbox("\u8bf7\u586b\u5165\u6b63\u786e\u7684\u9875\u7801!",1,QZBlog.Util.MSG_LIFTTIME.MIDDLE),!1;if(1>a||a>this._totalIndex)return QZBlog.Util.showMsgbox("\u6b64\u9875\u7801\u4e0d\u5b58\u5728!",
1,QZBlog.Util.MSG_LIFTTIME.MIDDLE),!1;a!=this._currentIndex&&this._showPage(a);try{/blog_output_data/.test(location.href)?QZBlog.Util.Statistic.sendPV("comment_btn_comfirm","blogtest.qzone.qq.com"):/blog/.test(location.href)&&QZBlog.Util.Statistic.sendPV("list_btn_confirm","blogtest.qzone.qq.com")}catch(b){}return!0},_showPage:function(a){this._currentIndex=a;this._updatePage();this._callback(this._currentIndex)},_updatePage:function(){for(var a=[],b=Math.max(this._currentIndex-3,1),c=Math.min(b+
6,this._totalIndex),d=b=Math.max(c-6,1);d<=c;++d)2<=b&&d==b?a.push('<a href="javascript:;" class="c_tx" onclick="QZBlog.Util.PageIndexManager.goDirectPage(1);return false;">1<a> <span class="mod_pagenav_more"><span>\u2026</span></span> '):c<=this._totalIndex-1&&d==c?a.push('<span class="mod_pagenav_more"><span>\u2026</span></span> <a href="javascript:;" class="c_tx" onclick="QZBlog.Util.PageIndexManager.goDirectPage('+this._totalIndex+');return false;">'+this._totalIndex+"</a> "):a.push(d!=this._currentIndex?
'<a href="javascript:;" class="c_tx" onclick="QZBlog.Util.PageIndexManager.goDirectPage('+d+');return false;">'+d+"</a> ":' <span class="current"><span>'+d+"</span></span> ");this._pageData.firstDisabled=1==this._currentIndex?!0:!1;this._pageData.nextDisabled=this._currentIndex==this._totalIndex?!0:!1;this._pageData.firstDisableClass=this._pageData.firstDisabled?"":"none";this._pageData.firstAvailClass=this._pageData.firstDisabled?"none":"";this._pageData.nextDisableClass=this._pageData.nextDisabled?
"":"none";this._pageData.nextAvailClass=this._pageData.nextDisabled?"none":"";this._pageData.centerPageHTML=a.join("");this._pageData.currentPage=this._currentIndex;for(d=0;d<this._containerArr.length;++d)this._containerArr[d].id&&(this._containerArr[d]=$(this._containerArr[d].id)),this._containerArr[d].innerHTML=doFill(this._templateHTML,{data:this._pageData}),QZONE.event.addEvent($("pageIndex_input"+this._pageData.index),"keypress",function(a){a=QZONE.event.getEvent(a);13==a.keyCode&&QZBlog.Util.PageIndexManager.goDirectPage(QZONE.event.getTarget().value.trim())}),
++this._pageData.index},_bInitialized:!1,_currentIndex:-1,_totalIndex:-1,_callback:null,_containerArr:null,_pageData:{firstDisabled:!1,centerPageHTML:!1,nextDisabled:"",currentPage:1,index:1},_templateHTML:'<%repeat_0 match="/data"%><div class="mod_pagenav"><p class="mod_pagenav_main"><span class="mod_pagenav_disable <%=@firstDisableClass%>"><span>\u4e0a\u4e00\u9875</span></span><a onclick="QZBlog.Util.PageIndexManager.goPage(-1);return false;" class="c_tx <%=@firstAvailClass%>" href="javascript:;">\u4e0a\u4e00\u9875</a> <span class="mod_pagenav_count"><%=@centerPageHTML%></span> <span class="mod_pagenav_disable <%=@nextDisableClass%>"><span>\u4e0b\u4e00\u9875</span></span><a class="c_tx <%=@nextAvailClass%>" onclick="QZBlog.Util.PageIndexManager.goPage(1);return false;" href="javascript:;">\u4e0b\u4e00\u9875</a> </p><p class="mod_pagenav_option"><span class="mod_pagenav_turn">\u8f6c\u5230<input class="textinput" type="text" id="pageIndex_input<%=@index%>" value="<%=@currentPage%>" /> \u9875 <button onclick="QZBlog.Util.PageIndexManager.goDirectPage($(\'pageIndex_input<%=@index%>\').value.trim());" type="button" class="bt_tx2">\u786e \u5b9a</button></p></div><%_repeat_0%>'};
QZBlog.Util.pwd2Verified=function(){return!(""==QZONE.FP._t.QZFL.dataCenter.get("pwd2sig")||"undefined"==typeof QZONE.FP._t.QZFL.dataCenter.get("pwd2sig"))};QZBlog.Util.clearPwd2Sig=function(){QZONE.FP._t.QZFL.dataCenter.del("pwd2sig")};QZBlog.Util.savePwd2Sig=function(a){QZONE.FP._t.QZFL.dataCenter.save("pwd2sig",a,"memory")};QZBlog.Util.getPwd2Sig=function(){return"undefined"==typeof QZONE.FP._t.QZFL.dataCenter.get("pwd2sig")?"":QZONE.FP._t.QZFL.dataCenter.get("pwd2sig")};
QZBlog.Util.queryPwdState=function(a,b){QZBlog.Util.pwd2Verified()?a():QZBlog.Util._doQueryPwdFrame("verify",a,b)};
QZBlog.Util._doQueryPwdFrame=function(a,b,c){QZBlog.Util.showMsgbox("\u6b63\u5728\u67e5\u8be2\u72ec\u7acb\u5bc6\u7801\uff0c\u8bf7\u7a0d\u5019\u2026\u2026",6,QZBlog.Util.MSG_LIFTTIME.MIDDLE);a=new QZBlog.Util.NetRequest({url:QZBlog.CGI_URL.get("pwd2c_query_iframe"),data:{uin:QZBlog.Logic.SpaceHostInfo.getUin(),action:a,redirecturl:"http://"+IMGCACHE_DOMAIN+IMGCACHE_BLOG_V5_PATH+"/pwd/callback.html",r:Math.random(),fupdate:1},method:"get",uniqueCGI:!0});a.onSuccess=function(a){a=a.data;window.nMaskID=
QZFL.maskLayout.create(5E3,document);window.pwdDialog=QZFL.dialog.create("",{src:a.iframeurl+"&ipwd_tg=window"},{width:370,height:290,useTween:!1,noBorder:!0,top:150});window.pwdDialog.onUnload=function(){b();QZFL.maskLayout.remove(window.nMaskID)}};a.onError=function(a){QZBlog.Util.showMsgbox(a||"\u670d\u52a1\u5668\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5",5,QZBlog.Util.MSG_LIFTTIME.MIDDLE);"function"==typeof c&&c()};a.send()};
QZBlog.Util.changePwd=function(){QZBlog.Util._doQueryPwdFrame("modify",QZONE.emptyFn)};function CloseAlert(){window.pwdDialog.onUnload=QZONE.emptyFn;window.pwdDialog.unload();QZFL.maskLayout.remove(window.nMaskID)}
QZBlog.Util.NamecardInitiator={loaded:!1,loadScript:function(){var a=new QZONE.jsLoader;a.onload=QZONE.event.bind(this,function(){this.loaded=!0});a.load("http://"+IMGCACHE_DOMAIN+"/qzone/v5/namecardv2.js",document,"utf-8")},initArea:function(a){this._checkReady(QZONE.event.bind(this,this.initArea,a))&&QZBlog.Util.TimerManager.setTimeout(function(){try{QZONE.namecard.init(a)}catch(b){}},2E3)},_checkReady:function(a){return this.loaded?!0:(QZBlog.Util.TimerManager.setTimeout(QZONE.event.bind(this,
a),100),!1)}};
QZBlog.Util.parseTimeString=function(a){var b=a.match(/^ *(\d{4})-(\d{1,2})-(\d{1,2}) *$/);return b&&3<b.length?new Date(parseInt(b[1]),parseInt(b[2])-1,parseInt(b[3])):(b=a.match(/^ *(\d{4})-(\d{1,2})-(\d{1,2}) +(\d{1,2}):(\d{1,2}):(\d{1,2}) *$/))&&6<b.length?new Date(parseInt(b[1]),parseInt(b[2])-1,parseInt(b[3]),parseInt(b[4]),parseInt(b[5]),parseInt(b[6])):(b=a.match(/^ *(\d{4})-(\d{1,2})-(\d{1,2}) +(\d{1,2}):(\d{1,2}):(\d{1,2})\.(\d{1,9}) *$/))&&7<b.length?new Date(parseInt(b[1]),parseInt(b[2])-
1,parseInt(b[3]),parseInt(b[4]),parseInt(b[5]),parseInt(b[6]),parseInt(b[7])):null};QZBlog.Util.createAd=function(a,b,c,d,e,f){c=void 0===c?1:c;a&&b&&b.nodeType&&("undefined"!=typeof QBS||f?(e=e||function(a){if(a=QZBlog.Util.renderAd(a,d))b.innerHTML=a,b.style.display=""},QBS&&QBS.get(a,b,c,!1,e)):QZFL.imports("http://"+IMGCACHE_DOMAIN+"/qzone/biz/comm/js/qbs.js",function(){QZBlog.Util.createAd(a,b,c,d,e,!0)}))};
QZBlog.Util.loadQBossAd=function(){var a=function(){var b=QZBlog.Util.getLoginIsVIP(),c="user-state-"+(b?"vip":"normal");QZFL.css.addClassName(document.body,c);QZFL.css.insertStyleSheet(null,"."+c+(b?" .showInVip":" .showInNoVip")+"{display:block !important;}");a=QZFL.emptyFn};return function(b,c){a();var d=QZBlog.Logic.isInPengyou?QZBlog.Util.getPengyouDecodeUin():QZBlog.Logic.SpaceHostInfo.getLoginUin(),d={uin:d||0,board_id:b},e="qzone_blog_qboss_ad"+b,f=PAGE_CACHE.get(e);f?c(f.extdata,f.adData,
f.response):(d=new QZBlog.Util.NetRequest({url:"http://boss.qzone.qq.com/fcg-bin/fcg_get_strategy",data:d,charset:"utf-8",isSilenderMode:!0}),d.onSuccess=function(a){var d=QZFL.object.route(a,"data."+b+".items.0")||{},f=d.extdata;f&&(c(f,d,a),PAGE_CACHE.add(e,{extdata:f,adData:d,response:a},3600))},d.send())}}();
QZBlog.Util.reportQBossState=function(a,b){var c={from:0,uin:QZBlog.Logic.SpaceHostInfo.getLoginUin(),qboper:b||2,bosstrace:a},d=new parent.Image;d.src=QZBlog.Util.mergeCgiUri("http://boss.qzone.qq.com/fcg-bin/fcg_rep_strategy",c);console.log("AD CLICK",d.src)};
QZBlog.Util.renderAd=function(a,b){if(!a||!a.data||!a.data.length)return"";var c=[];b=b||{};if("img"==b.type)for(var d=0;d<a.data.length;d++){var e=a.data[d];e.img&&(e.rl&&"void(0);"!=e.rl?c.push(['<a href="',e.rl,'" target="_blank" onclick="return QBS.click(\'',e.cl,'\',false,true);" title="',e.txt,'" style="',b.aStyle,'"><img src="',e.img,'" alt="',e.txt,'"/></a>'].join("")):c.push(["<span onclick=\"QBS.click('",e.cl,'\',false,true);" title="',e.txt,'" style="',b.aStyle,'"><img src="',e.img,'" alt="',
e.txt,'"/></span>'].join("")))}else if("textlink"==b.type)for(d=0;d<a.data.length;d++)e=a.data[d],c.push(['<a href="',e.rl,'" target="_blank" onclick="return QBS.click(\'',e.cl,'\',false,true);" style="',b.aStyle,'">',e.txt,"</a>"].join(""));return c.join("")};
QZBlog.Util.parseMentionStr=function(){var a=function(a){return a&&a.replace(/(%2C|%25|%7D)/g,function(a){return unescape(a).toInnerHTML()})};return function(b){if(!b||0>b.indexOf("@"))return b;b=b.replace(/%3A/g,":").replace(/%2C/g,",");return b=b.replace(/@\{uin:([^\}]*),nick:([^\}]*?)(?:,who:([^\}]*))?(?:,auto:([^\}]*))?\}/g,function(b,d,e){d=escape(d.toInnerHTML());return"<a href="+((/\D/g.test(d)?"http://xiaoyou.qq.com/index.php?mod=profile&u=":"http://user.qzone.qq.com/")+d)+' target="_blank">@'+
a(e)+"</a>"})}}();QZBlog.Util.protectMentionStr=function(a){return a.replace(/(@\{uin:[^\}]*,\s*nick:)([^\}]*?)(,|})/g,function(a,c,d,e){return c+d.toInnerHTML()+e})};
QZBlog.Logic.deleteBlog=function(a,b,c,d,e){a=QZFL.lang.isArray(a)?a.join("_"):a;d={uin:QZBlog.Logic.SpaceHostInfo.getLoginUin(),hostUin:QZBlog.Logic.SpaceHostInfo.getUin(),idList:a,blogType:d||0};e&&(d.delForce=!0);e=new QZBlog.Util.NetRequest({url:QZBlog.CGI_URL.get("del_blog"),data:d,method:"post",uniqueCGI:!0});e.onSuccess=function(a){QZBlog.Util.showMsgbox("\u5220\u9664\u6210\u529f\uff01",4,QZBlog.Util.MSG_LIFTTIME.MIDDLE);b&&b(a)};e.onError=function(a){c&&c(a)};e.send()};
QZBlog.Logic.setBlogTop=function(a,b){if(a){var c={uin:QZBlog.Logic.SpaceHostInfo.getLoginUin(),hostUin:QZBlog.Logic.SpaceHostInfo.getUin(),blogId:a.getID(),topFlag:a.getTopFlag()?0:1},c=new QZBlog.Util.NetRequest({url:QZBlog.CGI_URL.get("mod_blog_effect"),data:c,method:"post",uniqueCGI:!0});c.onSuccess=function(){QZBlog.Logic.refreshTopData();a.setTopFlag(!a.getTopFlag());a.updateRandomSeed();parent.BlogListNavigator.removePageData();var c=parent.g_oBlogInfoMgr.getBlogInfo(a.getID());parent.g_oBlogInfoMgr.removeBlogInfo(a.getID());
c&&(c.updateRandomSeed(),c.setTopFlag(a.getTopFlag()));"function"==typeof b&&b()};c.send()}};QZBlog.Logic.recommendBlog=function(a){QZBlog.Util.popupDialog("\u63a8\u8350\u65e5\u5fd7",{src:"/qzone/app/blog/dialog/recommend_blog_dlg.html?blogid="+a},340,265)};QZBlog.Logic.convertBlogToPrivate=function(a,b,c){QZBlog.Util.popupDialog("\u8f6c\u4e3a\u79c1\u5bc6\u65e5\u5fd7",{src:IMGCACHE_BLOG_V5_PATH+"/convert_blog_dlg.html?blogid="+a+"&mode="+(b?1:0)},398,185)};
QZBlog.Logic.refreshTopData=function(){parent.isRefreshTop=!0;PAGE_CACHE.clean("HostRecentBlogList")};QZBlog.Logic.clearMusicPlayer=function(){try{window.bTopPageMusicStop&&(QZONE.cookie.set("pausemusic","0"),parent.window.musicJSReady&&parent.Qplay(parent.getPlayingPos())),__flash__removeCallback=function(){},__flash_unloadHandler=function(){},__flash_savedUnloadHandler=function(){},g_insertSwfNum=0,clearTimeout(parent.g_nBlogMusicTimer),clearMusicData()}catch(a){}};
QZBlog.Logic.initMusicPlayer=function(){return function(){var a=document.getElementsByName("musicFlash**");if(0<a.length){for(var b=[],c=0;c<a.length;++c){var d=a[c].getAttribute("ubb");if(d=d.toRealStr().replace(/<|>/g,"").replace(/"|'/g,""))if(b.push(d),QZFL.userAgent.ie)a[c].id="musicFlash"+(b.length-1),9>QZFL.userAgent.ie&&(a[c].name="musicFlash"+(b.length-1));else{var e=7<d.split("|").length,f=parseInt(a[c].width,10),g=parseInt(a[c].height,10),h=e?200:120,e=e?386:360,k="http://"+IMGCACHE_DOMAIN+
"/music/musicbox_v2_1/img/MusicFlash.swf",l=document.createElement("span");l.style.cssText="display:inline-block; height:"+h+"px;width:"+e+"px; overflow:hidden; vertical-align:baseline";a[c].parentNode.replaceChild(l,a[c]);l.innerHTML='<object type="application/x-shockwave-flash" data="'+k+'" width="'+f+'" height="'+g+'" name="musicFlash'+(b.length-1)+'" id="musicFlash'+(b.length-1)+'" align="middle" ubb="'+d+'"><param name="movie" value="'+k+'" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" /><param name="play" value="true" /><param name="loop" value="true" /><param name="wmode" value="transparent" /><param name="scale" value="showall" /><param name="menu" value="true" /><param name="salign" value="" /><param name="allowScriptAccess" value="always" /></object></span>';
c--}}0<b.length&&(a=new QZONE.jsLoader,a.onload=function(){initMusicData.apply(null,b)},a.load("http://qzonestyle.gtimg.cn/music/musicbox_v2_1/js/musicblog_player.js",document,"GB2312"))}}}();
QZBlog.Logic.opCategory=function(a,b){var c={ADD:1,MODIFY:2,DELETE:3}[a.opType];if(12<a.cateName.replace(/[^\x00-\xff]/g,"hh").length)return alert("\u5bf9\u4e0d\u8d77,\u5206\u7c7b\u540d\u79f0\u957f\u5ea6\u4e0d\u80fd\u8d85\u8fc712\u4e2a\u5b57\u6bcd/6\u4e2a\u6c49\u5b57"),!1;if("\u8fd1\u671f\u65e5\u5fd7"==a.cateName||"\u5f80\u671f\u65e5\u5fd7"==a.cateName||a.cateName==parent.BLOG_DEFAULT_CATENAME)return alert("\u5bf9\u4e0d\u8d77\uff0c\u4e0d\u80fd\u4f7f\u7528\u201c"+a.cateName+"\u201d\u4f5c\u4e3a\u5206\u7c7b\u540d\u79f0"),
!1;c={hostUin:QZBlog.Logic.SpaceHostInfo.getUin(),cateName:a.cateName.replace(/[\x00-\x20 ]/g," ")||null,opType:c};"MODIFY"==a.opType?(c.oldCateName=a.oldCateName,c.oldCateHex=a.oldCateHex):"DELETE"==a.opType&&(c.cateHex=a.cateHex);c=new QZBlog.Util.NetRequest({url:QZBlog.CGI_URL.get("op_cate"),data:c,method:"post",uniqueCGI:!0});c.onSuccess=function(c){c.data.cateName=a.cateName;try{b&&b(c)}catch(e){}return!0};c.send()};
QZBlog.Logic.showAddCategoryDlg=function(a){parent.addBlogCategoryCallback=function(b){a(b);QZBlog.Util.closePopup()};QZBlog.Util.popupDialog("\u6dfb\u52a0\u65e5\u5fd7\u5206\u7c7b",{src:IMGCACHE_BLOG_V5_PATH+"/add_category_dlg.html"},380,100)};
QZBlog.Logic.setBlogSetting=function(a,b,c){a=a+"&uin="+QZBlog.Logic.SpaceHostInfo.getLoginUin()+"&pwd2sig="+QZBlog.Util.getPwd2Sig();var d=QZBlog.CGI_URL.get("blog_set_bitmap");a=new QZBlog.Util.NetRequest({url:d,data:a,method:"post",isSilenderMode:c});a.onSuccess=function(){b&&b()};a.send()};QZBlog.Logic.convertToBlog=function(a){parent.blogPopupCallback=function(b,c){a(b,c)};QZBlog.Util.popupDialog("\u8f6c\u4e3a\u65e5\u5fd7",{src:"/qzone/newblog/v5/convert_toblog_dlg.html"},482,183)};
QZBlog.Logic.setBlogRight=function(a,b){var c=a.getRightInfo();if(c){parent.blogPopupCallback=function(c,d){if(c){var e=QZBlog.CGI_URL.get("mod_blog_right"),k={uin:QZBlog.Logic.SpaceHostInfo.getLoginUin(),hostUin:QZBlog.Logic.SpaceHostInfo.getUin(),idList:a.getID(),rightType:c},l=[];if(2==c)l.push({cateid:1,groupid:2}),d&&d.noticeInfoFlag&&(k.feeds=1);else if(3==c){for(var m=[],n=0;n<d.length;n++)m.push(d[n].data),l.push({cateid:128,groupid:d[n].data});k.specUins=m.join(",")}else 4==c&&l.push({cateid:4,
groupid:4});e=new QZBlog.Util.NetRequest({url:e,data:k,method:"post",uniqueCGI:!0});e.onSuccess=function(){QZBlog.Util.showMsgbox("\u8bbe\u7f6e\u6210\u529f",4,QZBlog.Util.MSG_LIFTTIME.MIDDLE);var d=new parent.BlogRightInfo;d.convertJsonObject(l);a.setRightInfo(d);a.updateRandomSeed();a.setEffectBit(29,1==c?!1:!0);QZBlog.Logic.refreshTopData();b&&b()};e.send()}};var d="",e=c.getType();e==parent.BlogRightInfo.RIGHTTYPE.SPECIFIC&&(d=c.getUserIDList().join("|"));d||(d="");QZBlog.Util.popupDialog("\u6743\u9650\u8bbe\u7f6e",
{src:IMGCACHE_BLOG_V5_PATH+"/right_setting_dlg.html?specuins="+d+"&right="+e},482,78)}};
QZBlog.Logic.getCategoryInfo=function(a,b,c){if(!parent.g_oCateInfoMgr)return!1;!c&&0<parent.g_oCateInfoMgr.getCategoryCnt()?a&&a({data:parent.g_oCateInfoMgr.toJsonObject()}):(b=QZBlog.CGI_URL.get("get_abs")+"?"+QZBlog.Util.buildParam(QZBlog.Util.getNewBlogListUrlData({reqInfo:2})),b=new QZBlog.Util.NetRequest({url:b,method:"get"}),b.onSuccess=function(b){for(var c=0,f=0;f<b.data.cateInfo.categoryList.length;++f)c+=b.data.cateInfo.categoryList[f].num;b.data.cateInfo.maxarch=Math.max(0,b.data.blog_num-
c);b.data.cateInfo.blogNum=c;parent.g_oCateInfoMgr.convertJsonObject(b.data.cateInfo);a&&a(b)},b.send())};
QZBlog.Logic.setCategoryInfo=function(a,b,c){QZONE.FP.dialog=QZONE.FP.dialog||QZONE.FP._t.QZFL.dialog;QZFL.FP.dialog.create("\u4fee\u6539\u5206\u7c7b",{src:"/qzone/newblog/v5/change_category.html"},{showMask:!0,width:360,height:130,buttonConfig:[{type:QZFL.dialog.BUTTON_TYPE.Confirm,text:"\u786e\u5b9a",tips:"\u786e\u5b9a"},{type:QZFL.dialog.BUTTON_TYPE.Cancel,text:"\u53d6\u6d88",tips:"\u53d6\u6d88"}],onLoad:function(d){QZONE.FP.dialog.getById(d.id).onConfirm=function(){var d=this.dialogContent.getElementsByTagName("iframe")[0].contentWindow.getCategoryInfo();
d==b?QZBlog.Util.showMsgbox("\u60a8\u9009\u62e9\u7684\u5206\u7c7b\u540d\u4e0e\u539f\u5206\u7c7b\u540d\u76f8\u540c\u3002",2,QZBlog.Util.MSG_LIFTTIME.MIDDLE):(this._doChangeCategory=function(a,b,c,d){QZBlog.Util.showMsgbox("\u6b63\u5728\u63d0\u4ea4\u60a8\u7684\u8bf7\u6c42,\u8bf7\u7a0d\u5019...",6,QZBlog.Util.MSG_LIFTTIME.MIDDLE);var e=QZBlog.CGI_URL.get("mod_blog_cate");a={uin:QZBlog.Logic.SpaceHostInfo.getLoginUin(),hostUin:QZBlog.Logic.SpaceHostInfo.getUin(),cate:b.replace(/[\x00-\x20 ]/g," "),idList:a};
e=new QZBlog.Util.NetRequest({url:e,data:a,method:"post",uniqueCGI:!0});e.onSuccess=function(){QZBlog.Util.showMsgbox("\u4fee\u6539\u5206\u7c7b\u6210\u529f\uff01",4,QZBlog.Util.MSG_LIFTTIME.MIDDLE);QZBlog.Logic.refreshTopData();parent.g_oCateInfoMgr.clear();parent.BlogListNavigator.clear();parent.BlogListNavigator.removePageData();try{c(b)}catch(a){}};e.onError=function(a){QZBlog.Util.showMsgbox(a,1,QZBlog.Util.MSG_LIFTTIME.MIDDLE);try{d()}catch(b){}};e.send()},this._doChangeCategory(a,d.toRealStr(),
c,null))}}})};QZBlog.Logic.getDateInfo=function(a,b,c){if(parent.g_oCateInfoMgr.getDateInfo(a)&&!c)b&&b(parent.g_oCateInfoMgr.getDateInfo(a));else{c=QZBlog.CGI_URL.get("get_abs");var d={reqInfo:4,statYear:a};c=new QZBlog.Util.NetRequest({url:c,data:function(){return QZBlog.Util.getNewBlogListUrlData(d)},method:"get"});c.onSuccess=function(c){c=c.data;c.year=a;var d=new parent.BlogDateInfo;d.convertJsonObject(c);parent.g_oCateInfoMgr.setDateInfo(a,d);b&&b(d)};c.send()}};
QZBlog.Logic.getAuditCnt=function(a,b){var c;c="&needblog="+(a&1?1:0)+("&needmsgb="+(a&2?1:0));c+="&needphoto="+(a&4?1:0);c+="&needshuoshuo="+(a&8?1:0);c=QZBlog.CGI_URL.get("blog_get_unverifynum")+"?uin="+QZBlog.Logic.SpaceHostInfo.getUin()+c;c=new QZBlog.Util.NetRequest({url:c,method:"get",uniqueCGI:!0});c.onSuccess=function(a){b(a.data)};c.send()};
QZBlog.Logic.getBlogViewInfo=function(a,b){b=b||QZFL.emptyFn;QZBlog.Util.getSecureSettingInfo("disable_read_counter",function(c){c||(c=QZBlog.CGI_URL.get("get_count")+"?type=1&uinList="+QZBlog.Logic.SpaceHostInfo.getUin()+"&idList="+a.join("_")+"&r="+Math.random(),c=new QZBlog.Util.NetRequest({url:c,method:"get",isSilenderMode:!0}),c.onSuccess=function(a){b(a)},c.send())})};
QZBlog.Logic.getBlogCountInfo=function(a,b){QZBlog.Util.getSecureSettingInfo("disable_read_counter",function(c){c||(c=QZBlog.Util.buildParam({type:1,uinList:QZBlog.Logic.SpaceHostInfo.getUin(),idList:a.join("_"),r:Math.random()}),c=new QZBlog.Util.NetRequest({url:QZBlog.CGI_URL.get("get_count"),data:c,method:"get",isSilenderMode:!0}),c.onSuccess=function(a){var c={};(a=QZFL.object.route(a,"data.itemList"))&&a.length&&(QZFL.each(a,function(a){c[a.id]={read:a.read,reply:a.reply}}),b(c))},c.send())})};
QZBlog.Logic.searchTag=function(a,b){a&&0!=a.length&&(QZONE.FP.Search(a,{entryid:57,type:"blog",appname:"\u65e5\u5fd7",backurl:"/blog"+("undefined"!=typeof b?"/"+b:"")}),QZBlog.Util.Statistic.sendPV("blog-tag","searchact.qzone.qq.com"))};
QZBlog.Logic.searchBlog=function(){return function(a,b,c){var d;d=$("sosoForm");d||(d=document.createElement("form"),d.id="sosoForm",d.style.display="none",d.action="http://qzone.soso.com/qz.q",d.target="_blank",document.body.appendChild(d));a='<input type="hidden" name="sc" value="qz"/><input type="hidden" name="ch" value="s.qz.diary"/>'+("utf-8"==c?'<input type="hidden" name="ie" value="utf8"/>':"")+'<input type="hidden" name="ty" value="diary"/><input type="hidden" name="w" value="'+a+'"/><input type="hidden" name="'+
(b?'cid" value="qz.s.allsite" />':'cid" value="qz.s.insite" /><input type="hidden" name="site" value="'+QZBlog.Logic.SpaceHostInfo.getUin()+'" />');if(QZBlog.Logic.SpaceHostInfo.isValidLoginUin()){c=QZBlog.Logic.SpaceHostInfo.getLoginUin();var e="";c=parseInt(c);if(!(isNaN(c)||1E4>=c)){c=(new String(c)).split("");for(var f=0;f<c.length;++f)e+=String.fromCharCode(65+parseInt(c[f],10))}c='<input type="hidden" name="user" value="0'+e+'"/>'}else c="";d.innerHTML=a+c;d.submit();parent.UserBlogConfig.setSearchOption(b)}}();
QZBlog.Logic.getTweetStatus=function(){return!!QZONE.FP.getLoginBitmap(41)};
QZBlog.Util.synTweetCheckState=function(a,b){if(void 0===b){var c="http://"+(QZBlog.Logic.isInPengyou?"r.pengyou.com":"r.qzone.qq.com")+"/cgi-bin/right/get_qqbitmap.cgi?uin="+QZBlog.Util.getLoginUin()+"&g_tk="+QZBlog.Util.getToken()+"&ref="+(QZBlog.Logic.isInPengyou?"qqcampus":"qzone"),c=new QZONE.JSONGetter(c,void 0,null,"UTF-8");c.onSuccess=QZONE.event.bind(this,function(b){b&&b.item&&(b=b&&b.items[0]&&0<b.items[0].ugclog?!0:!1,a&&a(b))});c.send("_Callback")}else{var c="http://"+(QZBlog.Logic.isInPengyou?
"w.pengyou.com":"w.qzone.qq.com")+"/cgi-bin/right/set_qqbitmap.cgi",d={},d=QZBlog.Logic.isInPengyou?{uin:QZBlog.Util.getPengyouDecodeUin(),ugclog:b?1:-1}:{uin:QZBlog.Util.getLoginUin(),ugclog:b?1:-1},c=new QZONE.FormSender(c,"post",d,"UTF-8");c.onSuccess=function(a){};c.onError=function(a){};c.send()}};
QZBlog.Logic.procBlogContent=function(){var a=0,b=function(a){return c(a)&&/(.*)(\&|&amp;|\?)t=5($|&.*)/i.test(a)?a.replace(/(.*)(\&|&amp;|\?)t=5($|&)(.*)/i,"$1$2$4"):a},c=function(a){return/^http:\/\/\w+\.photo\.store\.qq\.com\//i.test(a)||/^http:\/\/\w+\.qpic\.cn\//i.test(a)},d=function(d,e){var h=d.getAttribute("orgSrc"),k=d.getAttribute("src");if(!QZBlog.Util.isNonsenseImg(h||k)){var l=a++,m=function(a,c){var d=parseInt(a.offsetWidth||a.style.width,10)||0,f=parseInt(a.offsetHeight||a.style.height,
10)||0;(d=QZBlog.Util.scaleRegion(d,f,e))&&QZFL.dom.setStyle(a,d);a.removeAttribute("orgSrc");QZFL.css.removeClassName(a,"QZBLOG_IMG_LOADING");a.setAttribute("data-img-idx",l);a.setAttribute("data-src",b(c))};!/loaded|complete/.test(d.readyState)&&!d.complete||QZBlog.Util.isNonsenseImg(d.src)?(QZFL.event.addEvent(d,"load",function(){QZBlog.Util.isNonsenseImg(this.src)||m(this,h||this.src)}),h&&(c(h)&&QZFL.userAgent.ie&&8<QZFL.userAgent.ie?QZONE.FP._t.seajs.use("photo.v7/common/webp/webp2Base64/webp2Base64",
function(a){a.getImgBase64({url:h+"&t=5",callback:function(a){console.log("base64 \u8f6c\u6362:",h+"&t=5");console.log("base64 \u8f6c\u6362\u7ed3\u679c:",a);d.src=a[0]}})}):d.src=h)):(console.log("\u56fe\u7247\u52a0\u8f7d\u5b8c\u6210 &\u3000\u975e\u900f\u660e\u5360\u4f4d\u56fe",d.src),m(d,k))}},e=function(a){a.getAttribute("data-webp-ctx-e")||(a.setAttribute("data-webp-ctx-e",1),QZFL.event.addEvent(a,"mousedown",function(a){var b=QZFL.event.getButton(a);a=QZFL.event.getTarget(a);"img"==a.nodeName.toLowerCase()&&
0!=b&&(b=a.getAttribute("data-src"))&&b!=a.src&&(console.log("webp \u53f3\u952e\u66ff\u6362\u56fe\u7247",b),a.removeAttribute("data-src"),a.src=b)}))};return function(a,b){console.log("\u5904\u7406\u65e5\u5fd7\u6b63\u6587\u5185\u5bb9");if(a){e(a);b=QZFL.object.extend({letterFlag:!1,previewMode:!1,maxPreloadCnt:1E6},b||{});var c=QZBlog.Util.isWideMode()?870:670;b.letterFlag&&(c=QZBlog.Util.isWideMode()?847:630);QZBlog.Util.isFreeMode()&&(c=QZBlog.Util.getFreeModeMaxMediaWidth());var k=a.getElementsByTagName("IMG");
QZFL.each(k,function(a){d(a,c)});flashList=a.getElementsByTagName("EMBED");QZFL.each(flashList,function(a){var b=parseInt(a.getAttribute("width"),10)||0,d=parseInt(a.getAttribute("width"),10)||0;b>c&&(a.style.width=c+"px",d&&0<c/b*d&&(a.style.height=c/b*d+"px"))});PageScheduler.blogInfo=PageScheduler.blogInfo||PageScheduler.curBlogInfo;if((b.previewMode||PageScheduler&&PageScheduler.blogInfo&&PageScheduler.blogInfo.getEffectBit(39))&&$("pagestyle")){var k=$("pagestyle").sheet||document.styleSheets.pagestyle,
l=QZBlog.Logic.getSpecialFontNameList(a.innerHTML);QZBlog.Logic.loadSpecialFontLib(k,l);0<l.length&&$("topHintArea")&&(QZONE.userAgent.ie||b.previewMode||($("topHintArea").innerHTML='<div class="hint"><strong class="icon_hint"><span>\u63d0\u793a</span></strong> <span>\u672c\u7bc7\u65e5\u5fd7\u4f7f\u7528\u4e86<a href="http://qzone.qq.com/helpcenter/yellow_info.htm?56" target="_blank" class="c_tx4">\u4e2a\u6027\u5b57\u4f53</a>\uff0c\u8bf7\u4f7f\u7528IE\u6d4f\u89c8\u5668\u67e5\u770b\u5b8c\u6574\u6548\u679c\u3002</span> <a href="javascript:void(0)" title="\u5173\u95ed" onclick="$(\'topHintArea\').style.display = \'none\';return false;" class="hint_close">\u5173\u95ed</a></div>'),
QZONE.userAgent.ie&&($("topHintArea").innerHTML='<div class="hint"><strong class="icon_hint"><span>\u63d0\u793a</span></strong> <span>\u60a8\u53ef\u4ee5<a href="javascript:;" onclick="InfoManager.switchSpecialFont(false);return false;" class="c_tx4">\u4f7f\u7528\u666e\u901a\u5b57\u4f53</a>\u67e5\u770b\uff0c\u4f7f\u7528\u4e2a\u6027\u5b57\u4f53\u7684\u90e8\u5206\u5c06\u6062\u590d\u4e3a\u5b8b\u4f53\uff0c\u6b64\u64cd\u4f5c\u6709\u53ef\u80fd\u6253\u4e71\u6587\u5b57\u73b0\u6709\u6392\u7248\u3002</span> <a href="javascript:void(0)" title="\u5173\u95ed" onclick="$(\'topHintArea\').style.display = \'none\';return false;" class="hint_close">\u5173\u95ed</a></div>'))}}}}();
QZBlog.Logic.appealBlog=function(){var a=function(a,c,d){QZBlog.Util.popupDialog("QQ\u7a7a\u95f4\u7533\u8bc9\u5e73\u53f0",{src:a},c,d);QZONE.FP._t.appeal_onClose=function(){QZONE.FP.closePopup()}};return function(b){b="http://jubao.qq.com/cn/appeal/appeal?appname=appeal&subapp=qzone_blog&jubaotype=article&uin="+QZBlog.Logic.SpaceHostInfo.getUin()+"&blogid="+b;a(b,629,510)}}();
QZBlog.Logic.showReport=function(a){var b=parent.$("jubao_div");b||(b=QZONE.dom.createElementIn("div",parent.document.body,!1,{id:"jubao_div",style:"position:absolute; display:none; width:633px; height:483px; z-index: 999; padding:0; margin:0px;"}));parent.jubao_onResize=function(a,b){if(login_wnd=$("jubao_div"))login_wnd.style.width=a+"px",login_wnd.style.height=b+"px",login_wnd.style.visibility="hidden",login_wnd.style.visibility="visible"};parent.jubao_onClose=function(){if(login_wnd=parent.$("jubao_div"))login_wnd.style.display=
"none",login_wnd.innerHTML="",parent.reportMaskID&&QZONE.maskLayout.remove(parent.reportMaskID),parent.reportMaskID=0};var c=(parent.QZONE.dom.getClientWidth()-633)/2+parent.QZONE.dom.getScrollLeft(),d=Math.max((parent.QZONE.dom.getClientHeight()-483)/2+parent.QZONE.dom.getScrollTop(),0);b.style.left=c+"px";b.style.top=d+"px";parent.reportMaskID=QZFL.maskLayout.create(100,parent.document);b.innerHTML='<iframe name="jubao_frame" id="jubao_frame" frameborder="0" scrolling="no" width="100%" height="100%" src="'+
a+'"></iframe>';b.style.display=""};QZBlog.Logic.gotoVipInfo=function(a){a==QZBlog.Util.getSpaceUin()?QZBlog.Util.toApp("/yellowgrade"):window.open("http://user.qzone.qq.com/"+a+"/yellowgrade")};
QZBlog.Logic.getSpecialFontNameList=function(a){var b=[];a=a.replace(/<(font|span)([^>]+)>/ig,function(a,d,e){if((d=/face=("|)([^"\s]+)("|)/.exec(e))&&d[2])for(var f in g_specialFontList)-1!=d[2].indexOf(g_specialFontList[f].className)&&b.push(f);return a});a=a.replace(/<(div|span)([^>]+)>/ig,function(a,d,e){if((d=/font-family:([^;^"]+)/ig.exec(e))&&d[1])for(var f in g_specialFontList)-1!=d[1].indexOf(g_specialFontList[f].className)&&b.push(f);return a});return QZFL.lang.uniqueArray(b)};
var g_specialFontList={"\u8c46\u8c46\u4f53":{exampleName:"\u8c46\u8c46\u4f53",classPrefix:"qzone_font_dou",className:"dou",urlPath:"http://"+IMGCACHE_DOMAIN+"/qzonestyle/act/font/eot/TCDOU0.eot",fontLibLoaded:!1,tryid:50,succid:51},"\u6843\u5fc3\u4f53":{exampleName:"\u6843\u5fc3\u4f53",classPrefix:"qzone_font_tao",className:"tao",urlPath:"http://"+IMGCACHE_DOMAIN+"/qzonestyle/act/font/eot/TCLOVE0.eot",fontLibLoaded:!1,tryid:52,succid:53},"\u5c0f\u82b1\u4f53":{exampleName:"\u5c0f\u82b1\u4f53",classPrefix:"qzone_font_xiaohua",
className:"xiaohua",urlPath:"http://"+IMGCACHE_DOMAIN+"/qzonestyle/act/font/eot/TCHUAYU0.eot",fontLibLoaded:!1,tryid:58,succid:59},"\u6e05\u79c0\u4f53":{exampleName:"\u6e05\u79c0\u4f53",classPrefix:"qzone_font_qingxiu",className:"qingxiu",urlPath:"http://"+IMGCACHE_DOMAIN+"/qzonestyle/act/font/eot/TCQINGX0.eot",fontLibLoaded:!1,tryid:79,succid:80},"\u82b1\u5377\u4f53":{exampleName:"\u82b1\u5377\u4f53",classPrefix:"qzone_font_huajuan",className:"huajuan",urlPath:"http://"+IMGCACHE_DOMAIN+"/qzonestyle/act/font/eot/TCHUAJU0.eot",
fontLibLoaded:!1,tryid:81,succid:82},"\u94a2\u7b14\u4f53":{exampleName:"\u94a2\u7b14\u4f53",classPrefix:"qzone_font_pen",className:"fountainpen",urlPath:"http://"+IMGCACHE_DOMAIN+"/qzonestyle/act/font/eot/TCGANGB0.eot",fontLibLoaded:!1,tryid:211,succid:212}};
QZBlog.Logic.loadSpecialFontLib=function(a,b){if(a&&QZFL.userAgent.ie){for(var c="",d=0;d<b.length;++d)g_specialFontList[b[d]]&&(c+="\n@font-face { font-family: "+g_specialFontList[b[d]].className+"; font-style: normal;font-weight: normal;src: url("+g_specialFontList[b[d]].urlPath+");}\n");0<c.length&&setTimeout(function(){a.cssText+=c},50)}};
QZBlog.Logic.enableSpeicialFontEffect=function(a,b){if(a){var c=[],d;for(d in g_specialFontList)c.push(g_specialFontList[d].className);b?(c=RegExp("(font-family: )("+c.join("|")+")(_dump)","ig"),a.cssText=a.cssText.replace(c,function(a,b,c){return b+c})):(c=RegExp("(font-family: )("+c.join("|")+")","ig"),a.cssText=a.cssText.replace(c,function(a,b,c){return b+c+"_dump"}));delete c}};
QZBlog.Logic.showHotMess=function(a){var b=$("hot_mess");b&&("undefined"!=typeof QBS||a?QBS.get("qzone_blogright_txt_1",b,1,!1,function(a){try{b.innerHTML="<a href='"+a.data[0]._l+"' target='_blank' onclick='return QBS.click(\""+a.data[0].cl+"\", false, true);' class='unline'>"+a.data[0].txt+"</a>",QZONE.css.removeClassName(b,"none")}catch(d){}}):QZFL.imports("http://"+IMGCACHE_DOMAIN+"/qzone/biz/comm/js/qbs.js",function(){QZBlog.Logic.showHotMess(!0)}))};
QZBlog.Logic.showPageHintInfo=function(a,b,c){"string"!=typeof c&&(c="pageHintArea");var d=$(c);d||(d=QZONE.dom.createElementIn("div",b?b:document.body,!0,{id:c}));d.innerHTML='<div class="hint"><strong class="icon_hint"><span>\u63d0\u793a</span></strong><span>'+a+'</span><a href="javascript:;" title="\u5173\u95ed\u63d0\u793a" class="hint_close" onclick="$(\''+c+"').style.display='none';return false;\"></a></div>";d.style.display=""};
(function(){var a={};this.tmpl=function c(d,e){var f=/\W/.test(d)?new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+d.replace(/[\r\t\n]/g," ").replace(/'(?=[^%]*%>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<%=(.+?)%>/g,"',$1,'").split("<%").join("');").split("%>").join("p.push('")+"');}return p.join('');"):a[d]=a[d]||c(document.getElementById(d).innerHTML);return e?f(e):f}})();
QZBlog.Util.getSplitTime=function(a){var b=new Date(a.replace(/-/g,"/")),c=new Date;return b.getFullYear()?(b=c-b,0>b?"":36E5>=b?"1\u5c0f\u65f6\u5185":36E5<b&&864E5>=b?Math.ceil(b/36E5)+"\u5c0f\u65f6\u5185":864E5<b?a.replace(/\s.*$/,""):""):""};QZBlog.Logic.showClinic=function(a){QZBlog.Util.popupDialog("\u6e29\u99a8\u63d0\u793a",{src:IMGCACHE_BLOG_V5_PATH+"/clinic_tip.html?flag="+("undefined"==typeof a?!0:!1)},450,170)};
function getCursorPosition(a){var b={text:"",start:0,end:0};a.focus();if(a.setSelectionRange)b.start=a.selectionStart,b.end=a.selectionEnd,b.text=b.start!=b.end?a.value.substring(b.start,b.end):"";else if(document.selection){var c,d=document.selection.createRange(),e=document.body.createTextRange();e.moveToElementText(a);b.text=d.text;b.bookmark=d.getBookmark();for(c=0;0>e.compareEndPoints("StartToStart",d)&&0!==d.moveStart("character",-1);c++)"\n"==a.value.charAt(c)&&c++;b.start=c;b.end=b.text.length+
b.start}return b}function setCursorPosition(a,b){if(a.setSelectionRange)a.focus(),a.setSelectionRange(b.start,b.end);else if(a.createTextRange){var c=a.createTextRange();a.value.length===b.start?c.collapse(!1):c.moveToBookmark(b.bookmark);c.select()}}
try{$("pageContainer")&&($("pageContainer").className=QZBlog.Util.isWideMode()?"blog big_mode_blog":QZBlog.Util.isSmallMode()?"blog mini_mode_blog":"blog full_mode_blog"),QZONE.event.addEvent(window,"beforeunload",function(){QZBlog.Util.TimerManager.clear()}),"blog.qq.com"==location.host&&QZFL.imports("http://js.aq.qq.com/js/aq_common.js")}catch(err$$18){};
